"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActAlgo_pb2
from . import ActAutoControl_pb2
from . import ActInstrument_pb2
from . import ActOrders_pb2
from . import ActStrategy_pb2
from . import ActTicks_pb2
from . import ActTrades_pb2
from . import ActTypes_pb2
from . import ActValuation_pb2
from . import DataExchangeAPI_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ProtocolVersion:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ProtocolVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ProtocolVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    APV_SET_ALGO_STATUS: _ProtocolVersion.ValueType  # 1
    APV_TERMINATE_ALGO: _ProtocolVersion.ValueType  # 2
    """	!!!!!!!!!! don't forget to update ACT_PROTOCOL_VERSION below when adding a new version"""

class ProtocolVersion(_ProtocolVersion, metaclass=_ProtocolVersionEnumTypeWrapper):
    """Versioning of the Act protocol"""
    pass

APV_SET_ALGO_STATUS: ProtocolVersion.ValueType  # 1
APV_TERMINATE_ALGO: ProtocolVersion.ValueType  # 2
"""	!!!!!!!!!! don't forget to update ACT_PROTOCOL_VERSION below when adding a new version"""

global___ProtocolVersion = ProtocolVersion


class _LatestVersion:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LatestVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LatestVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACT_PROTOCOL_VERSION: _LatestVersion.ValueType  # 2
    """	always set to the latest version above"""

class LatestVersion(_LatestVersion, metaclass=_LatestVersionEnumTypeWrapper):
    pass

ACT_PROTOCOL_VERSION: LatestVersion.ValueType  # 2
"""	always set to the latest version above"""

global___LatestVersion = LatestVersion


class _SubProtocolType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _SubProtocolTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SubProtocolType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUB_PROTO_DEX: _SubProtocolType.ValueType  # 0
    SUB_PROTO_ORDER: _SubProtocolType.ValueType  # 1
    SUB_PROTO_ACT: _SubProtocolType.ValueType  # 3
    SUB_PROTO_AUTOCONTROL: _SubProtocolType.ValueType  # 4
    SUB_PROTO_STRATEGY: _SubProtocolType.ValueType  # 5
    SUB_PROTO_TRADE: _SubProtocolType.ValueType  # 6
    SUB_PROTO_VALUATION: _SubProtocolType.ValueType  # 7
    SUB_PROTO_TICK: _SubProtocolType.ValueType  # 8
    SUB_PROTO_ALGO: _SubProtocolType.ValueType  # 9
    SUB_PROTO_INSTRUMENT: _SubProtocolType.ValueType  # 11
class SubProtocolType(_SubProtocolType, metaclass=_SubProtocolTypeEnumTypeWrapper):
    """Request messages are passed from client->actant and are identified by RequestType enum"""
    pass

SUB_PROTO_DEX: SubProtocolType.ValueType  # 0
SUB_PROTO_ORDER: SubProtocolType.ValueType  # 1
SUB_PROTO_ACT: SubProtocolType.ValueType  # 3
SUB_PROTO_AUTOCONTROL: SubProtocolType.ValueType  # 4
SUB_PROTO_STRATEGY: SubProtocolType.ValueType  # 5
SUB_PROTO_TRADE: SubProtocolType.ValueType  # 6
SUB_PROTO_VALUATION: SubProtocolType.ValueType  # 7
SUB_PROTO_TICK: SubProtocolType.ValueType  # 8
SUB_PROTO_ALGO: SubProtocolType.ValueType  # 9
SUB_PROTO_INSTRUMENT: SubProtocolType.ValueType  # 11
global___SubProtocolType = SubProtocolType


class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_LOGIN: _RequestType.ValueType  # 0
    REQ_LOGOUT: _RequestType.ValueType  # 1
class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    """Request messages are passed from client to actant and are identified by RequestType enum"""
    pass

REQ_LOGIN: RequestType.ValueType  # 0
REQ_LOGOUT: RequestType.ValueType  # 1
global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_LOGIN: _ResponseType.ValueType  # 0
    RESP_CONNECTION_STATUS_BROADCAST: _ResponseType.ValueType  # 3
class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    """Response messages are passed from actant to client and are identified by ResponseType enum"""
    pass

RESP_LOGIN: ResponseType.ValueType  # 0
RESP_CONNECTION_STATUS_BROADCAST: ResponseType.ValueType  # 3
global___ResponseType = ResponseType


class _FailureAction:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _FailureActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FailureAction.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACTION_VISUAL_WARNING: _FailureAction.ValueType  # 0
    ACTION_HOLD_ALL: _FailureAction.ValueType  # 1
    ACTION_SELECTIVE_HOLD: _FailureAction.ValueType  # 2
class FailureAction(_FailureAction, metaclass=_FailureActionEnumTypeWrapper):
    pass

ACTION_VISUAL_WARNING: FailureAction.ValueType  # 0
ACTION_HOLD_ALL: FailureAction.ValueType  # 1
ACTION_SELECTIVE_HOLD: FailureAction.ValueType  # 2
global___FailureAction = FailureAction


class _SessionOption:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _SessionOptionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SessionOption.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SESSION_OPTION_UNUSED: _SessionOption.ValueType  # 0
    SESSION_OPTION_BROADCAST_CONNECTION_STATUS: _SessionOption.ValueType  # 3
class SessionOption(_SessionOption, metaclass=_SessionOptionEnumTypeWrapper):
    pass

SESSION_OPTION_UNUSED: SessionOption.ValueType  # 0
SESSION_OPTION_BROADCAST_CONNECTION_STATUS: SessionOption.ValueType  # 3
global___SessionOption = SessionOption


class _ConnectionStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ConnectionStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConnectionStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONNECTION_DISCONNECTED: _ConnectionStatus.ValueType  # 0
    CONNECTION_CONNECTING: _ConnectionStatus.ValueType  # 1
    CONNECTION_CONNECTED: _ConnectionStatus.ValueType  # 2
class ConnectionStatus(_ConnectionStatus, metaclass=_ConnectionStatusEnumTypeWrapper):
    pass

CONNECTION_DISCONNECTED: ConnectionStatus.ValueType  # 0
CONNECTION_CONNECTING: ConnectionStatus.ValueType  # 1
CONNECTION_CONNECTED: ConnectionStatus.ValueType  # 2
global___ConnectionStatus = ConnectionStatus


class ActLoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    APPNAME_FIELD_NUMBER: builtins.int
    FAILUREACTIONS_FIELD_NUMBER: builtins.int
    SESSIONOPTIONS_FIELD_NUMBER: builtins.int
    CLIENTPROPERTIES_FIELD_NUMBER: builtins.int
    username: typing.Text
    password: typing.Text
    appname: typing.Text
    @property
    def failureActions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___FailureAction.ValueType]: ...
    @property
    def sessionOptions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___SessionOption.ValueType]: ...
    @property
    def clientProperties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.Property]: ...
    def __init__(self,
        *,
        username: typing.Optional[typing.Text] = ...,
        password: typing.Optional[typing.Text] = ...,
        appname: typing.Optional[typing.Text] = ...,
        failureActions: typing.Optional[typing.Iterable[global___FailureAction.ValueType]] = ...,
        sessionOptions: typing.Optional[typing.Iterable[global___SessionOption.ValueType]] = ...,
        clientProperties: typing.Optional[typing.Iterable[ActTypes_pb2.Property]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["appname",b"appname","password",b"password","username",b"username"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["appname",b"appname","clientProperties",b"clientProperties","failureActions",b"failureActions","password",b"password","sessionOptions",b"sessionOptions","username",b"username"]) -> None: ...
global___ActLoginRequest = ActLoginRequest

class ActLoginResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    LINKTIME_FIELD_NUMBER: builtins.int
    NODE_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    HASALLOCATIONS_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    ACTPROTOCOLVERSION_FIELD_NUMBER: builtins.int
    Version: typing.Text
    """	Actant version (e.g. 3.76.0.0)"""

    LinkTime: typing.Text
    Node: typing.Text
    User: typing.Text
    """	Windows user"""

    hasAllocations: builtins.bool
    """	Multi-user mode or other way to set ALLOCATIONS correctly in DEX"""

    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.Property]: ...
    actProtocolVersion: builtins.int
    """	allows simple test if a new feature is available"""

    def __init__(self,
        *,
        Version: typing.Optional[typing.Text] = ...,
        LinkTime: typing.Optional[typing.Text] = ...,
        Node: typing.Optional[typing.Text] = ...,
        User: typing.Optional[typing.Text] = ...,
        hasAllocations: typing.Optional[builtins.bool] = ...,
        properties: typing.Optional[typing.Iterable[ActTypes_pb2.Property]] = ...,
        actProtocolVersion: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["LinkTime",b"LinkTime","Node",b"Node","User",b"User","Version",b"Version","actProtocolVersion",b"actProtocolVersion","hasAllocations",b"hasAllocations"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["LinkTime",b"LinkTime","Node",b"Node","User",b"User","Version",b"Version","actProtocolVersion",b"actProtocolVersion","hasAllocations",b"hasAllocations","properties",b"properties"]) -> None: ...
global___ActLoginResponse = ActLoginResponse

class Connection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: typing.Text
    status: global___ConnectionStatus.ValueType
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        status: typing.Optional[global___ConnectionStatus.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name",b"name","status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","status",b"status"]) -> None: ...
global___Connection = Connection

class ActRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    LOGINREQUEST_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    """	unique id for a request assigned by client app"""

    @property
    def loginRequest(self) -> global___ActLoginRequest: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        loginRequest: typing.Optional[global___ActLoginRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","loginRequest",b"loginRequest","requestType",b"requestType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","loginRequest",b"loginRequest","requestType",b"requestType"]) -> None: ...
global___ActRequest = ActRequest

class ActResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    SESSIONID_FIELD_NUMBER: builtins.int
    LOGINRESPONSE_FIELD_NUMBER: builtins.int
    CONNECTIONS_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    """	clientId sent in request"""

    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    sessionId: builtins.int
    """	id assigned to each client application during login"""

    @property
    def loginResponse(self) -> global___ActLoginResponse: ...
    @property
    def connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Connection]: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        sessionId: typing.Optional[builtins.int] = ...,
        loginResponse: typing.Optional[global___ActLoginResponse] = ...,
        connections: typing.Optional[typing.Iterable[global___Connection]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","loginResponse",b"loginResponse","operationStatus",b"operationStatus","responseType",b"responseType","sessionId",b"sessionId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","connections",b"connections","loginResponse",b"loginResponse","operationStatus",b"operationStatus","responseType",b"responseType","sessionId",b"sessionId"]) -> None: ...
global___ActResponse = ActResponse

class Request(google.protobuf.message.Message):
    """Requests are passed from client system and will contain only one of the specific requests"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBPROTOCOLTYPE_FIELD_NUMBER: builtins.int
    DEXREQUEST_FIELD_NUMBER: builtins.int
    ORDERREQUEST_FIELD_NUMBER: builtins.int
    ACTREQUEST_FIELD_NUMBER: builtins.int
    AUTOCONTROLREQUEST_FIELD_NUMBER: builtins.int
    STRATEGYREQUEST_FIELD_NUMBER: builtins.int
    TRADEREQUEST_FIELD_NUMBER: builtins.int
    VALUATIONREQUEST_FIELD_NUMBER: builtins.int
    TICKREQUEST_FIELD_NUMBER: builtins.int
    ALGOREQUEST_FIELD_NUMBER: builtins.int
    INSTRUMENTREQUEST_FIELD_NUMBER: builtins.int
    subProtocolType: global___SubProtocolType.ValueType
    @property
    def dexRequest(self) -> DataExchangeAPI_pb2.Request: ...
    @property
    def orderRequest(self) -> ActOrders_pb2.Request: ...
    @property
    def actRequest(self) -> global___ActRequest: ...
    @property
    def autoControlRequest(self) -> ActAutoControl_pb2.Request: ...
    @property
    def strategyRequest(self) -> ActStrategy_pb2.Request: ...
    @property
    def tradeRequest(self) -> ActTrades_pb2.Request: ...
    @property
    def valuationRequest(self) -> ActValuation_pb2.Request: ...
    @property
    def tickRequest(self) -> ActTicks_pb2.Request: ...
    @property
    def algoRequest(self) -> ActAlgo_pb2.Request: ...
    @property
    def instrumentRequest(self) -> ActInstrument_pb2.Request: ...
    def __init__(self,
        *,
        subProtocolType: typing.Optional[global___SubProtocolType.ValueType] = ...,
        dexRequest: typing.Optional[DataExchangeAPI_pb2.Request] = ...,
        orderRequest: typing.Optional[ActOrders_pb2.Request] = ...,
        actRequest: typing.Optional[global___ActRequest] = ...,
        autoControlRequest: typing.Optional[ActAutoControl_pb2.Request] = ...,
        strategyRequest: typing.Optional[ActStrategy_pb2.Request] = ...,
        tradeRequest: typing.Optional[ActTrades_pb2.Request] = ...,
        valuationRequest: typing.Optional[ActValuation_pb2.Request] = ...,
        tickRequest: typing.Optional[ActTicks_pb2.Request] = ...,
        algoRequest: typing.Optional[ActAlgo_pb2.Request] = ...,
        instrumentRequest: typing.Optional[ActInstrument_pb2.Request] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["actRequest",b"actRequest","algoRequest",b"algoRequest","autoControlRequest",b"autoControlRequest","dexRequest",b"dexRequest","instrumentRequest",b"instrumentRequest","orderRequest",b"orderRequest","strategyRequest",b"strategyRequest","subProtocolType",b"subProtocolType","tickRequest",b"tickRequest","tradeRequest",b"tradeRequest","valuationRequest",b"valuationRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["actRequest",b"actRequest","algoRequest",b"algoRequest","autoControlRequest",b"autoControlRequest","dexRequest",b"dexRequest","instrumentRequest",b"instrumentRequest","orderRequest",b"orderRequest","strategyRequest",b"strategyRequest","subProtocolType",b"subProtocolType","tickRequest",b"tickRequest","tradeRequest",b"tradeRequest","valuationRequest",b"valuationRequest"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Responses are passed from actant system and will contain only one of the specific responses."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBPROTOCOLTYPE_FIELD_NUMBER: builtins.int
    DEXRESPONSE_FIELD_NUMBER: builtins.int
    ORDERRESPONSE_FIELD_NUMBER: builtins.int
    ACTRESPONSE_FIELD_NUMBER: builtins.int
    AUTOCONTROLRESPONSE_FIELD_NUMBER: builtins.int
    STRATEGYRESPONSE_FIELD_NUMBER: builtins.int
    TRADERESPONSE_FIELD_NUMBER: builtins.int
    VALUATIONRESPONSE_FIELD_NUMBER: builtins.int
    TICKRESPONSE_FIELD_NUMBER: builtins.int
    INSTRUMENTRESPONSE_FIELD_NUMBER: builtins.int
    ALGORESPONSE_FIELD_NUMBER: builtins.int
    subProtocolType: global___SubProtocolType.ValueType
    @property
    def dexResponse(self) -> DataExchangeAPI_pb2.Response: ...
    @property
    def orderResponse(self) -> ActOrders_pb2.Response: ...
    @property
    def actResponse(self) -> global___ActResponse: ...
    @property
    def autoControlResponse(self) -> ActAutoControl_pb2.Response: ...
    @property
    def strategyResponse(self) -> ActStrategy_pb2.Response: ...
    @property
    def tradeResponse(self) -> ActTrades_pb2.Response: ...
    @property
    def valuationResponse(self) -> ActValuation_pb2.Response: ...
    @property
    def tickResponse(self) -> ActTicks_pb2.Response: ...
    @property
    def instrumentResponse(self) -> ActInstrument_pb2.Response: ...
    @property
    def algoResponse(self) -> ActAlgo_pb2.Response: ...
    def __init__(self,
        *,
        subProtocolType: typing.Optional[global___SubProtocolType.ValueType] = ...,
        dexResponse: typing.Optional[DataExchangeAPI_pb2.Response] = ...,
        orderResponse: typing.Optional[ActOrders_pb2.Response] = ...,
        actResponse: typing.Optional[global___ActResponse] = ...,
        autoControlResponse: typing.Optional[ActAutoControl_pb2.Response] = ...,
        strategyResponse: typing.Optional[ActStrategy_pb2.Response] = ...,
        tradeResponse: typing.Optional[ActTrades_pb2.Response] = ...,
        valuationResponse: typing.Optional[ActValuation_pb2.Response] = ...,
        tickResponse: typing.Optional[ActTicks_pb2.Response] = ...,
        instrumentResponse: typing.Optional[ActInstrument_pb2.Response] = ...,
        algoResponse: typing.Optional[ActAlgo_pb2.Response] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["actResponse",b"actResponse","algoResponse",b"algoResponse","autoControlResponse",b"autoControlResponse","dexResponse",b"dexResponse","instrumentResponse",b"instrumentResponse","orderResponse",b"orderResponse","strategyResponse",b"strategyResponse","subProtocolType",b"subProtocolType","tickResponse",b"tickResponse","tradeResponse",b"tradeResponse","valuationResponse",b"valuationResponse"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["actResponse",b"actResponse","algoResponse",b"algoResponse","autoControlResponse",b"autoControlResponse","dexResponse",b"dexResponse","instrumentResponse",b"instrumentResponse","orderResponse",b"orderResponse","strategyResponse",b"strategyResponse","subProtocolType",b"subProtocolType","tickResponse",b"tickResponse","tradeResponse",b"tradeResponse","valuationResponse",b"valuationResponse"]) -> None: ...
global___Response = Response
