"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActTypes_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_AUTOCONTROL_UPDATE: _RequestType.ValueType  # 0
    REQ_GET_PARAMETER_ALIAS: _RequestType.ValueType  # 2
    REQ_UPDATE_PARAMETER_ALIAS: _RequestType.ValueType  # 3
    REQ_RESET_MM_PROTECTION: _RequestType.ValueType  # 4
    REQ_UPDATE_AUTOMATION_SAFETY: _RequestType.ValueType  # 5
    """REQ_SAFETY_ACTION = x;
    	future extensions
    	- retrieve/update custom automation profiles
    """

class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    """Hold automation based on profiles
    message SafetyAction
    {
    	repeated string product = 1;		//	if no product is specified, it's a global panic action accross all products
    	optional string newIId = 2;
    	optional string oldIId = 3;

    	optional string safetyProfile = 4;	//	predefined values: 'Masshold', 'SelectiveHold'
    }

    Request messages are passed from client->actant and are identified by RequestType enum
    """
    pass

REQ_AUTOCONTROL_UPDATE: RequestType.ValueType  # 0
REQ_GET_PARAMETER_ALIAS: RequestType.ValueType  # 2
REQ_UPDATE_PARAMETER_ALIAS: RequestType.ValueType  # 3
REQ_RESET_MM_PROTECTION: RequestType.ValueType  # 4
REQ_UPDATE_AUTOMATION_SAFETY: RequestType.ValueType  # 5
"""REQ_SAFETY_ACTION = x;
	future extensions
	- retrieve/update custom automation profiles
"""

global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_AUTOCONTROL_UPDATE: _ResponseType.ValueType  # 0
    """	confirms the initial message"""

    RESP_PRODUCT_AUTOMATION: _ResponseType.ValueType  # 1
    """	additional response per ProductAutomationResponse"""

    RESP_GET_PARAMETER_ALIAS: _ResponseType.ValueType  # 2
    RESP_UPDATE_PARAMETER_ALIAS: _ResponseType.ValueType  # 3
    RESP_RESET_MM_PROTECTION: _ResponseType.ValueType  # 4
    RESP_UPDATE_AUTOMATION_SAFETY: _ResponseType.ValueType  # 5
    """RESP_SAFETY_ACTION = x;"""

class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    """Response messages are passed from actant->client and are identified by ResponseType enum"""
    pass

RESP_AUTOCONTROL_UPDATE: ResponseType.ValueType  # 0
"""	confirms the initial message"""

RESP_PRODUCT_AUTOMATION: ResponseType.ValueType  # 1
"""	additional response per ProductAutomationResponse"""

RESP_GET_PARAMETER_ALIAS: ResponseType.ValueType  # 2
RESP_UPDATE_PARAMETER_ALIAS: ResponseType.ValueType  # 3
RESP_RESET_MM_PROTECTION: ResponseType.ValueType  # 4
RESP_UPDATE_AUTOMATION_SAFETY: ResponseType.ValueType  # 5
"""RESP_SAFETY_ACTION = x;"""

global___ResponseType = ResponseType


class AutomationUpdate(google.protobuf.message.Message):
    """The interactive id sent by the client application with every request to guarantee unique identification
    of all requests. This helps avoid race conditions and allows proper sequencing when new actions
    are taken without waiting for results of previous ones.
    IIds are string that contain two numbers separated by : representing session id and request within session

    Single automation status change request
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    AUTOCONTROLTYPE_FIELD_NUMBER: builtins.int
    AUTOMATIONSTATUS_FIELD_NUMBER: builtins.int
    autoControlType: typing.Text
    automationStatus: typing.Text
    """	the following fields are left out in the first version
    	- status change reason (masshold reason)
    	- flags for conflict resolution (e.g. release hitting quotes...)
    """

    def __init__(self,
        *,
        autoControlType: typing.Optional[typing.Text] = ...,
        automationStatus: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["autoControlType",b"autoControlType","automationStatus",b"automationStatus"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["autoControlType",b"autoControlType","automationStatus",b"automationStatus"]) -> None: ...
global___AutomationUpdate = AutomationUpdate

class ProductAutomationUpdate(google.protobuf.message.Message):
    """Update automation status for a product"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRODUCT_FIELD_NUMBER: builtins.int
    NEWIID_FIELD_NUMBER: builtins.int
    OLDIID_FIELD_NUMBER: builtins.int
    STATUSCHANGES_FIELD_NUMBER: builtins.int
    product: typing.Text
    newIId: typing.Text
    oldIId: typing.Text
    @property
    def statusChanges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AutomationUpdate]: ...
    def __init__(self,
        *,
        product: typing.Optional[typing.Text] = ...,
        newIId: typing.Optional[typing.Text] = ...,
        oldIId: typing.Optional[typing.Text] = ...,
        statusChanges: typing.Optional[typing.Iterable[global___AutomationUpdate]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["newIId",b"newIId","oldIId",b"oldIId","product",b"product"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["newIId",b"newIId","oldIId",b"oldIId","product",b"product","statusChanges",b"statusChanges"]) -> None: ...
global___ProductAutomationUpdate = ProductAutomationUpdate

class ProductAutomationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRODUCT_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    product: typing.Text
    @property
    def operationStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.OperationStatus]: ...
    def __init__(self,
        *,
        product: typing.Optional[typing.Text] = ...,
        operationStatus: typing.Optional[typing.Iterable[ActTypes_pb2.OperationStatus]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["product",b"product"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operationStatus",b"operationStatus","product",b"product"]) -> None: ...
global___ProductAutomationResponse = ProductAutomationResponse

class ParameterAlias(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PIPARAMETERNAMES_FIELD_NUMBER: builtins.int
    PEPARAMETERNAMES_FIELD_NUMBER: builtins.int
    NUMPEPARAMETERS_FIELD_NUMBER: builtins.int
    PIWPARAMETERNAMES_FIELD_NUMBER: builtins.int
    PIParameterNames: typing.Text
    PEParameterNames: typing.Text
    NumPEParameters: builtins.int
    PIWParameterNames: typing.Text
    def __init__(self,
        *,
        PIParameterNames: typing.Optional[typing.Text] = ...,
        PEParameterNames: typing.Optional[typing.Text] = ...,
        NumPEParameters: typing.Optional[builtins.int] = ...,
        PIWParameterNames: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["NumPEParameters",b"NumPEParameters","PEParameterNames",b"PEParameterNames","PIParameterNames",b"PIParameterNames","PIWParameterNames",b"PIWParameterNames"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["NumPEParameters",b"NumPEParameters","PEParameterNames",b"PEParameterNames","PIParameterNames",b"PIParameterNames","PIWParameterNames",b"PIWParameterNames"]) -> None: ...
global___ParameterAlias = ParameterAlias

class AutomationSafetySettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRODUCT_FIELD_NUMBER: builtins.int
    AUTOSAFETYINTERVAL_FIELD_NUMBER: builtins.int
    AUTOSAFETYMAXHITS_FIELD_NUMBER: builtins.int
    product: typing.Text
    AutoSafetyInterval: builtins.float
    AutoSafetyMaxHits: builtins.int
    def __init__(self,
        *,
        product: typing.Optional[typing.Text] = ...,
        AutoSafetyInterval: typing.Optional[builtins.float] = ...,
        AutoSafetyMaxHits: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["AutoSafetyInterval",b"AutoSafetyInterval","AutoSafetyMaxHits",b"AutoSafetyMaxHits","product",b"product"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["AutoSafetyInterval",b"AutoSafetyInterval","AutoSafetyMaxHits",b"AutoSafetyMaxHits","product",b"product"]) -> None: ...
global___AutomationSafetySettings = AutomationSafetySettings

class Request(google.protobuf.message.Message):
    """Requests are passed from client system and will contain only one of the specific requests"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    AUTOMATIONUPDATES_FIELD_NUMBER: builtins.int
    PARAMETERALIAS_FIELD_NUMBER: builtins.int
    PRODUCT_FIELD_NUMBER: builtins.int
    AUTOMATIONSAFETYSETTINGS_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    @property
    def automationUpdates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProductAutomationUpdate]: ...
    @property
    def parameterAlias(self) -> global___ParameterAlias:
        """repeated SafetyAction safetyActions = 4;"""
        pass
    product: typing.Text
    @property
    def automationSafetySettings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AutomationSafetySettings]: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        automationUpdates: typing.Optional[typing.Iterable[global___ProductAutomationUpdate]] = ...,
        parameterAlias: typing.Optional[global___ParameterAlias] = ...,
        product: typing.Optional[typing.Text] = ...,
        automationSafetySettings: typing.Optional[typing.Iterable[global___AutomationSafetySettings]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","parameterAlias",b"parameterAlias","product",b"product","requestType",b"requestType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["automationSafetySettings",b"automationSafetySettings","automationUpdates",b"automationUpdates","clientId",b"clientId","parameterAlias",b"parameterAlias","product",b"product","requestType",b"requestType"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Responses are passed from actant system and will contain only one of the specific responses."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    AUTOMATIONRESPONSE_FIELD_NUMBER: builtins.int
    PARAMETERALIAS_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    @property
    def automationResponse(self) -> global___ProductAutomationResponse: ...
    @property
    def parameterAlias(self) -> global___ParameterAlias: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        automationResponse: typing.Optional[global___ProductAutomationResponse] = ...,
        parameterAlias: typing.Optional[global___ParameterAlias] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["automationResponse",b"automationResponse","clientId",b"clientId","operationStatus",b"operationStatus","parameterAlias",b"parameterAlias","responseType",b"responseType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["automationResponse",b"automationResponse","clientId",b"clientId","operationStatus",b"operationStatus","parameterAlias",b"parameterAlias","responseType",b"responseType"]) -> None: ...
global___Response = Response
