# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActAlgo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ActTypes_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rActAlgo.proto\x12\x07\x41\x63tAlgo\x1a\x0e\x41\x63tTypes.proto\"3\n\x0fNamedInstrument\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ninstrument\x18\x02 \x01(\t\"\xc7\x01\n\x19\x43reateDirectActionRequest\x12\x18\n\x10\x64irectActionName\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x61seInstrument\x18\x02 \x01(\t\x12\x37\n\x15\x61\x64\x64itionalInstruments\x18\x03 \x03(\x0b\x32\x18.ActAlgo.NamedInstrument\x12)\n\x0finputParameters\x18\x04 \x03(\x0b\x32\x10.ActAPI.Property\x12\x14\n\x0c\x61\x63tionStatus\x18\x05 \x01(\t\"J\n\x1a\x43reateDirectActionResponse\x12\x12\n\nactionName\x18\x01 \x01(\t\x12\x18\n\x10\x61utomationStatus\x18\x02 \x01(\t\"\xd2\x01\n\x07Request\x12)\n\x0brequestType\x18\x01 \x01(\x0e\x32\x14.ActAlgo.RequestType\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x11\x12\x45\n\x19\x63reateDirectActionRequest\x18\x05 \x01(\x0b\x32\".ActAlgo.CreateDirectActionRequest\x12\x10\n\x08\x61lgoName\x18\x06 \x01(\t\x12\x31\n\rcontrolStatus\x18\x07 \x01(\x0e\x32\x1a.ActAlgo.AlgoControlStatus\"\xd6\x01\n\x08Response\x12+\n\x0cresponseType\x18\x01 \x01(\x0e\x32\x15.ActAlgo.ResponseType\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x11\x12\x30\n\x0foperationStatus\x18\x03 \x01(\x0b\x32\x17.ActAPI.OperationStatus\x12G\n\x1a\x63reateDirectActionResponse\x18\x06 \x01(\x0b\x32#.ActAlgo.CreateDirectActionResponse\x12\x10\n\x08\x61lgoName\x18\t \x01(\t*O\n\x11\x41lgoControlStatus\x12\x0f\n\x0b\x41\x43S_Unknown\x10\x00\x12\x0b\n\x07\x41\x43S_Off\x10\x01\x12\x0e\n\nACS_Manual\x10\x02\x12\x0c\n\x08\x41\x43S_Auto\x10\x03*\\\n\x0bRequestType\x12\x1c\n\x18REQ_CREATE_DIRECT_ACTION\x10\x02\x12\x17\n\x13REQ_SET_ALGO_STATUS\x10\x04\x12\x16\n\x12REQ_TERMINATE_ALGO\x10\x05*`\n\x0cResponseType\x12\x1d\n\x19RESP_CREATE_DIRECT_ACTION\x10\x02\x12\x18\n\x14RESP_SET_ALGO_STATUS\x10\x03\x12\x17\n\x13RESP_TERMINATE_ALGO\x10\x04')

_ALGOCONTROLSTATUS = DESCRIPTOR.enum_types_by_name['AlgoControlStatus']
AlgoControlStatus = enum_type_wrapper.EnumTypeWrapper(_ALGOCONTROLSTATUS)
_REQUESTTYPE = DESCRIPTOR.enum_types_by_name['RequestType']
RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
_RESPONSETYPE = DESCRIPTOR.enum_types_by_name['ResponseType']
ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
ACS_Unknown = 0
ACS_Off = 1
ACS_Manual = 2
ACS_Auto = 3
REQ_CREATE_DIRECT_ACTION = 2
REQ_SET_ALGO_STATUS = 4
REQ_TERMINATE_ALGO = 5
RESP_CREATE_DIRECT_ACTION = 2
RESP_SET_ALGO_STATUS = 3
RESP_TERMINATE_ALGO = 4


_NAMEDINSTRUMENT = DESCRIPTOR.message_types_by_name['NamedInstrument']
_CREATEDIRECTACTIONREQUEST = DESCRIPTOR.message_types_by_name['CreateDirectActionRequest']
_CREATEDIRECTACTIONRESPONSE = DESCRIPTOR.message_types_by_name['CreateDirectActionResponse']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
NamedInstrument = _reflection.GeneratedProtocolMessageType('NamedInstrument', (_message.Message,), {
  'DESCRIPTOR' : _NAMEDINSTRUMENT,
  '__module__' : 'ActAlgo_pb2'
  # @@protoc_insertion_point(class_scope:ActAlgo.NamedInstrument)
  })
_sym_db.RegisterMessage(NamedInstrument)

CreateDirectActionRequest = _reflection.GeneratedProtocolMessageType('CreateDirectActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDIRECTACTIONREQUEST,
  '__module__' : 'ActAlgo_pb2'
  # @@protoc_insertion_point(class_scope:ActAlgo.CreateDirectActionRequest)
  })
_sym_db.RegisterMessage(CreateDirectActionRequest)

CreateDirectActionResponse = _reflection.GeneratedProtocolMessageType('CreateDirectActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDIRECTACTIONRESPONSE,
  '__module__' : 'ActAlgo_pb2'
  # @@protoc_insertion_point(class_scope:ActAlgo.CreateDirectActionResponse)
  })
_sym_db.RegisterMessage(CreateDirectActionResponse)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'ActAlgo_pb2'
  # @@protoc_insertion_point(class_scope:ActAlgo.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'ActAlgo_pb2'
  # @@protoc_insertion_point(class_scope:ActAlgo.Response)
  })
_sym_db.RegisterMessage(Response)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALGOCONTROLSTATUS._serialized_start=803
  _ALGOCONTROLSTATUS._serialized_end=882
  _REQUESTTYPE._serialized_start=884
  _REQUESTTYPE._serialized_end=976
  _RESPONSETYPE._serialized_start=978
  _RESPONSETYPE._serialized_end=1074
  _NAMEDINSTRUMENT._serialized_start=42
  _NAMEDINSTRUMENT._serialized_end=93
  _CREATEDIRECTACTIONREQUEST._serialized_start=96
  _CREATEDIRECTACTIONREQUEST._serialized_end=295
  _CREATEDIRECTACTIONRESPONSE._serialized_start=297
  _CREATEDIRECTACTIONRESPONSE._serialized_end=371
  _REQUEST._serialized_start=374
  _REQUEST._serialized_end=584
  _RESPONSE._serialized_start=587
  _RESPONSE._serialized_end=801
# @@protoc_insertion_point(module_scope)
