# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActInstrument.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ActTypes_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x41\x63tInstrument.proto\x12\rActInstrument\x1a\x0e\x41\x63tTypes.proto\"\xf4\x01\n\x14InstrumentDefinition\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x16\n\x0einstrumentType\x18\x03 \x01(\t\x12\x12\n\nexpiration\x18\x04 \x01(\t\x12\x0e\n\x06strike\x18\x05 \x01(\x12\x12\x11\n\tpriceStep\x18\x06 \x01(\t\x12\x14\n\x0c\x63ontractSize\x18\x07 \x01(\x01\x12\x15\n\rmultiLineName\x18\x08 \x01(\t\x12\x14\n\x0c\x64\x65liverables\x18\t \x03(\t\x12\r\n\x05isOTC\x18\n \x01(\x08\x12\x16\n\x0e\x65xercisability\x18\x0b \x01(\t\"\x86\x01\n\x07Request\x12/\n\x0brequestType\x18\x01 \x01(\x0e\x32\x1a.ActInstrument.RequestType\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x11\x12\x38\n\x0binstruments\x18\x03 \x03(\x0b\x32#.ActInstrument.InstrumentDefinition\"\xbb\x01\n\x08Response\x12\x31\n\x0cresponseType\x18\x02 \x01(\x0e\x32\x1b.ActInstrument.ResponseType\x12\x10\n\x08\x63lientId\x18\x03 \x01(\x11\x12\x30\n\x0foperationStatus\x18\x04 \x01(\x0b\x32\x17.ActAPI.OperationStatus\x12\x38\n\x0binstruments\x18\x01 \x03(\x0b\x32#.ActInstrument.InstrumentDefinition*(\n\x0bRequestType\x12\x19\n\x15REQ_CREATE_OTC_OPTION\x10\x01*I\n\x0cResponseType\x12\x1d\n\x19RESP_INSTRUMENT_STREAMING\x10\x00\x12\x1a\n\x16RESP_CREATE_OTC_OPTION\x10\x01')

_REQUESTTYPE = DESCRIPTOR.enum_types_by_name['RequestType']
RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
_RESPONSETYPE = DESCRIPTOR.enum_types_by_name['ResponseType']
ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
REQ_CREATE_OTC_OPTION = 1
RESP_INSTRUMENT_STREAMING = 0
RESP_CREATE_OTC_OPTION = 1


_INSTRUMENTDEFINITION = DESCRIPTOR.message_types_by_name['InstrumentDefinition']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
InstrumentDefinition = _reflection.GeneratedProtocolMessageType('InstrumentDefinition', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTDEFINITION,
  '__module__' : 'ActInstrument_pb2'
  # @@protoc_insertion_point(class_scope:ActInstrument.InstrumentDefinition)
  })
_sym_db.RegisterMessage(InstrumentDefinition)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'ActInstrument_pb2'
  # @@protoc_insertion_point(class_scope:ActInstrument.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'ActInstrument_pb2'
  # @@protoc_insertion_point(class_scope:ActInstrument.Response)
  })
_sym_db.RegisterMessage(Response)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTTYPE._serialized_start=628
  _REQUESTTYPE._serialized_end=668
  _RESPONSETYPE._serialized_start=670
  _RESPONSETYPE._serialized_end=743
  _INSTRUMENTDEFINITION._serialized_start=55
  _INSTRUMENTDEFINITION._serialized_end=299
  _REQUEST._serialized_start=302
  _REQUEST._serialized_end=436
  _RESPONSE._serialized_start=439
  _RESPONSE._serialized_end=626
# @@protoc_insertion_point(module_scope)
