"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActTypes_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_CREATE_OTC_OPTION: _RequestType.ValueType  # 1
class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    """Request messages are passed from client->actant and are identified by RequestType enum"""
    pass

REQ_CREATE_OTC_OPTION: RequestType.ValueType  # 1
global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_INSTRUMENT_STREAMING: _ResponseType.ValueType  # 0
    RESP_CREATE_OTC_OPTION: _ResponseType.ValueType  # 1
class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    """Response messages are passed from actant->client and are identified by ResponseType enum"""
    pass

RESP_INSTRUMENT_STREAMING: ResponseType.ValueType  # 0
RESP_CREATE_OTC_OPTION: ResponseType.ValueType  # 1
global___ResponseType = ResponseType


class InstrumentDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    PRODUCT_FIELD_NUMBER: builtins.int
    INSTRUMENTTYPE_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    STRIKE_FIELD_NUMBER: builtins.int
    PRICESTEP_FIELD_NUMBER: builtins.int
    CONTRACTSIZE_FIELD_NUMBER: builtins.int
    MULTILINENAME_FIELD_NUMBER: builtins.int
    DELIVERABLES_FIELD_NUMBER: builtins.int
    ISOTC_FIELD_NUMBER: builtins.int
    EXERCISABILITY_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    product: typing.Text
    instrumentType: typing.Text
    expiration: typing.Text
    strike: builtins.int
    """	price"""

    priceStep: typing.Text
    contractSize: builtins.float
    multiLineName: typing.Text
    @property
    def deliverables(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    isOTC: builtins.bool
    exercisability: typing.Text
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        product: typing.Optional[typing.Text] = ...,
        instrumentType: typing.Optional[typing.Text] = ...,
        expiration: typing.Optional[typing.Text] = ...,
        strike: typing.Optional[builtins.int] = ...,
        priceStep: typing.Optional[typing.Text] = ...,
        contractSize: typing.Optional[builtins.float] = ...,
        multiLineName: typing.Optional[typing.Text] = ...,
        deliverables: typing.Optional[typing.Iterable[typing.Text]] = ...,
        isOTC: typing.Optional[builtins.bool] = ...,
        exercisability: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["contractSize",b"contractSize","exercisability",b"exercisability","expiration",b"expiration","instrument",b"instrument","instrumentType",b"instrumentType","isOTC",b"isOTC","multiLineName",b"multiLineName","priceStep",b"priceStep","product",b"product","strike",b"strike"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["contractSize",b"contractSize","deliverables",b"deliverables","exercisability",b"exercisability","expiration",b"expiration","instrument",b"instrument","instrumentType",b"instrumentType","isOTC",b"isOTC","multiLineName",b"multiLineName","priceStep",b"priceStep","product",b"product","strike",b"strike"]) -> None: ...
global___InstrumentDefinition = InstrumentDefinition

class Request(google.protobuf.message.Message):
    """Requests are passed from client system and will contain only one of the specific requests"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    INSTRUMENTS_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    @property
    def instruments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InstrumentDefinition]: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        instruments: typing.Optional[typing.Iterable[global___InstrumentDefinition]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","requestType",b"requestType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","instruments",b"instruments","requestType",b"requestType"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Responses are passed from actant system and will contain only one of the specific responses."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    INSTRUMENTS_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    @property
    def instruments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InstrumentDefinition]: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        instruments: typing.Optional[typing.Iterable[global___InstrumentDefinition]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","instruments",b"instruments","operationStatus",b"operationStatus","responseType",b"responseType"]) -> None: ...
global___Response = Response
