"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActAlgo_pb2
from . import ActPort_pb2
from . import ActTypes_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_ORDER_SEQ: _RequestType.ValueType  # 0
    REQ_ORDER_METADATA: _RequestType.ValueType  # 1
    REQ_ORDER_VALIDATION: _RequestType.ValueType  # 2
    REQ_STOP_ORDER_SUBSCRIPTION: _RequestType.ValueType  # 4
    """	REQ_START_ORDER_SUBSCRIPTION = 3;"""

    REQ_MARKET_EVENT: _RequestType.ValueType  # 5
    """	send market event, data in addOrder"""

    REQ_GET_ORDER_LIMITS: _RequestType.ValueType  # 6
    REQ_SET_ORDER_LIMITS: _RequestType.ValueType  # 7
class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    """Request messages are passed from client->actant and are identified by RequestType enum"""
    pass

REQ_ORDER_SEQ: RequestType.ValueType  # 0
REQ_ORDER_METADATA: RequestType.ValueType  # 1
REQ_ORDER_VALIDATION: RequestType.ValueType  # 2
REQ_STOP_ORDER_SUBSCRIPTION: RequestType.ValueType  # 4
"""	REQ_START_ORDER_SUBSCRIPTION = 3;"""

REQ_MARKET_EVENT: RequestType.ValueType  # 5
"""	send market event, data in addOrder"""

REQ_GET_ORDER_LIMITS: RequestType.ValueType  # 6
REQ_SET_ORDER_LIMITS: RequestType.ValueType  # 7
global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_ORDER_SEQ: _ResponseType.ValueType  # 0
    RESP_ADD_ORDER: _ResponseType.ValueType  # 1
    RESP_UPDATE_ORDER: _ResponseType.ValueType  # 2
    RESP_DELETE_ORDER: _ResponseType.ValueType  # 3
    RESP_METADATA: _ResponseType.ValueType  # 4
    RESP_ORDER_VALIDATION: _ResponseType.ValueType  # 5
    RESP_ORDER_SUBSCRIPTION: _ResponseType.ValueType  # 6
    RESP_MARKET_EVENT: _ResponseType.ValueType  # 7
    RESP_GET_ORDER_LIMITS: _ResponseType.ValueType  # 8
    RESP_SET_ORDER_LIMITS: _ResponseType.ValueType  # 9
class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    """Response messages are passed from actant->client and are identified by ResponseType enum"""
    pass

RESP_ORDER_SEQ: ResponseType.ValueType  # 0
RESP_ADD_ORDER: ResponseType.ValueType  # 1
RESP_UPDATE_ORDER: ResponseType.ValueType  # 2
RESP_DELETE_ORDER: ResponseType.ValueType  # 3
RESP_METADATA: ResponseType.ValueType  # 4
RESP_ORDER_VALIDATION: ResponseType.ValueType  # 5
RESP_ORDER_SUBSCRIPTION: ResponseType.ValueType  # 6
RESP_MARKET_EVENT: ResponseType.ValueType  # 7
RESP_GET_ORDER_LIMITS: ResponseType.ValueType  # 8
RESP_SET_ORDER_LIMITS: ResponseType.ValueType  # 9
global___ResponseType = ResponseType


class AddOrder(google.protobuf.message.Message):
    """The interactive id sent by the client application with every request to guarantee unique identification
    of all requests. This helps avoid race conditions and allows proper sequencing when new actions
    are taken without waiting for results of previous ones.
    IIds are string that contain two numbers separated by : representing session id and request within session

    Add order message
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    NEWIID_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SCALEDQUANTITY_FIELD_NUMBER: builtins.int
    DECQUANTITY_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    ORDERTYPE_FIELD_NUMBER: builtins.int
    NODEFAULTVALUES_FIELD_NUMBER: builtins.int
    DESTINATION_FIELD_NUMBER: builtins.int
    ROUTE_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    FREEFORM_FIELD_NUMBER: builtins.int
    OPENCLOSE_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    COUNTERPART_FIELD_NUMBER: builtins.int
    IGNOREPRICELIMIT_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    newIId: typing.Text
    """	new orders don't yet have an order key"""

    price: builtins.int
    """	order specification (required)"""

    scaledQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decQuantity: builtins.int
    """	quantity with decimals"""

    side: typing.Text
    orderType: typing.Text
    noDefaultValues: builtins.bool
    """	additional order details
    	when set to true, the server will use the values as is
    """

    destination: typing.Text
    """	empty fields will not be initialized with default values
    	MIC if destination isn't local to the market in instrument
    """

    route: typing.Text
    """	Route to which the order should be sent (native or execution vendor)"""

    account: typing.Text
    freeForm: typing.Text
    openClose: typing.Text
    """	"Open"/"Close" """

    flags: typing.Text
    """	order flags"""

    expiration: typing.Text
    """	YYYYMMDD"""

    counterpart: typing.Text
    ignorePriceLimit: builtins.bool
    """override the price limit check"""

    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.Property]: ...
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        newIId: typing.Optional[typing.Text] = ...,
        price: typing.Optional[builtins.int] = ...,
        scaledQuantity: typing.Optional[builtins.int] = ...,
        decQuantity: typing.Optional[builtins.int] = ...,
        side: typing.Optional[typing.Text] = ...,
        orderType: typing.Optional[typing.Text] = ...,
        noDefaultValues: typing.Optional[builtins.bool] = ...,
        destination: typing.Optional[typing.Text] = ...,
        route: typing.Optional[typing.Text] = ...,
        account: typing.Optional[typing.Text] = ...,
        freeForm: typing.Optional[typing.Text] = ...,
        openClose: typing.Optional[typing.Text] = ...,
        flags: typing.Optional[typing.Text] = ...,
        expiration: typing.Optional[typing.Text] = ...,
        counterpart: typing.Optional[typing.Text] = ...,
        ignorePriceLimit: typing.Optional[builtins.bool] = ...,
        properties: typing.Optional[typing.Iterable[ActTypes_pb2.Property]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account",b"account","counterpart",b"counterpart","decQuantity",b"decQuantity","destination",b"destination","expiration",b"expiration","flags",b"flags","freeForm",b"freeForm","ignorePriceLimit",b"ignorePriceLimit","instrument",b"instrument","newIId",b"newIId","noDefaultValues",b"noDefaultValues","openClose",b"openClose","orderType",b"orderType","price",b"price","route",b"route","scaledQuantity",b"scaledQuantity","side",b"side"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account",b"account","counterpart",b"counterpart","decQuantity",b"decQuantity","destination",b"destination","expiration",b"expiration","flags",b"flags","freeForm",b"freeForm","ignorePriceLimit",b"ignorePriceLimit","instrument",b"instrument","newIId",b"newIId","noDefaultValues",b"noDefaultValues","openClose",b"openClose","orderType",b"orderType","price",b"price","properties",b"properties","route",b"route","scaledQuantity",b"scaledQuantity","side",b"side"]) -> None: ...
global___AddOrder = AddOrder

class UpdateOrder(google.protobuf.message.Message):
    """Update order message"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    ORDERKEY_FIELD_NUMBER: builtins.int
    NEWIID_FIELD_NUMBER: builtins.int
    OLDIID_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SCALEDQUANTITY_FIELD_NUMBER: builtins.int
    DECQUANTITY_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    FREEFORM_FIELD_NUMBER: builtins.int
    OPENCLOSE_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    COUNTERPART_FIELD_NUMBER: builtins.int
    IGNOREPRICELIMIT_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    orderKey: typing.Text
    newIId: typing.Text
    oldIId: typing.Text
    price: builtins.int
    """	fields that can be updated"""

    scaledQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decQuantity: builtins.int
    """	quantity with decimals"""

    account: typing.Text
    """	we don't allow changing side, order type, destination and route"""

    freeForm: typing.Text
    openClose: typing.Text
    """	"Open"/"Close" """

    flags: typing.Text
    """	order flags"""

    expiration: typing.Text
    """	YYYYMMDD"""

    counterpart: typing.Text
    ignorePriceLimit: builtins.bool
    """override the price limit check"""

    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.Property]: ...
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        orderKey: typing.Optional[typing.Text] = ...,
        newIId: typing.Optional[typing.Text] = ...,
        oldIId: typing.Optional[typing.Text] = ...,
        price: typing.Optional[builtins.int] = ...,
        scaledQuantity: typing.Optional[builtins.int] = ...,
        decQuantity: typing.Optional[builtins.int] = ...,
        account: typing.Optional[typing.Text] = ...,
        freeForm: typing.Optional[typing.Text] = ...,
        openClose: typing.Optional[typing.Text] = ...,
        flags: typing.Optional[typing.Text] = ...,
        expiration: typing.Optional[typing.Text] = ...,
        counterpart: typing.Optional[typing.Text] = ...,
        ignorePriceLimit: typing.Optional[builtins.bool] = ...,
        properties: typing.Optional[typing.Iterable[ActTypes_pb2.Property]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account",b"account","counterpart",b"counterpart","decQuantity",b"decQuantity","expiration",b"expiration","flags",b"flags","freeForm",b"freeForm","ignorePriceLimit",b"ignorePriceLimit","instrument",b"instrument","newIId",b"newIId","oldIId",b"oldIId","openClose",b"openClose","orderKey",b"orderKey","price",b"price","scaledQuantity",b"scaledQuantity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account",b"account","counterpart",b"counterpart","decQuantity",b"decQuantity","expiration",b"expiration","flags",b"flags","freeForm",b"freeForm","ignorePriceLimit",b"ignorePriceLimit","instrument",b"instrument","newIId",b"newIId","oldIId",b"oldIId","openClose",b"openClose","orderKey",b"orderKey","price",b"price","properties",b"properties","scaledQuantity",b"scaledQuantity"]) -> None: ...
global___UpdateOrder = UpdateOrder

class DeleteOrder(google.protobuf.message.Message):
    """Delete order message"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    ORDERKEY_FIELD_NUMBER: builtins.int
    NEWIID_FIELD_NUMBER: builtins.int
    OLDIID_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    orderKey: typing.Text
    newIId: typing.Text
    oldIId: typing.Text
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        orderKey: typing.Optional[typing.Text] = ...,
        newIId: typing.Optional[typing.Text] = ...,
        oldIId: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["instrument",b"instrument","newIId",b"newIId","oldIId",b"oldIId","orderKey",b"orderKey"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["instrument",b"instrument","newIId",b"newIId","oldIId",b"oldIId","orderKey",b"orderKey"]) -> None: ...
global___DeleteOrder = DeleteOrder

class MetadataRequest(google.protobuf.message.Message):
    """Metadata request details"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    BBOTYPE_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    bboType: typing.Text
    """	"Main" (default), "Foreign", "Best", "Indicative", "Modifier" """

    side: typing.Text
    """	"Buy", "Sell" """

    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        bboType: typing.Optional[typing.Text] = ...,
        side: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bboType",b"bboType","instrument",b"instrument","side",b"side"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bboType",b"bboType","instrument",b"instrument","side",b"side"]) -> None: ...
global___MetadataRequest = MetadataRequest

class OrderOperationResult(google.protobuf.message.Message):
    """Order operation result is received for every order operation: add, update, delete
    It contains
    - Operation status that indicates whether the operation succeeded
    - New and old interactive ids that were sent with the request
    - OrderKey of the order acted upon, this key is uniquely identifying an order within the target actant system
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORDERKEY_FIELD_NUMBER: builtins.int
    NEWIID_FIELD_NUMBER: builtins.int
    OLDIID_FIELD_NUMBER: builtins.int
    orderKey: typing.Text
    newIId: typing.Text
    oldIId: typing.Text
    def __init__(self,
        *,
        orderKey: typing.Optional[typing.Text] = ...,
        newIId: typing.Optional[typing.Text] = ...,
        oldIId: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["newIId",b"newIId","oldIId",b"oldIId","orderKey",b"orderKey"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["newIId",b"newIId","oldIId",b"oldIId","orderKey",b"orderKey"]) -> None: ...
global___OrderOperationResult = OrderOperationResult

class OrderPropertyDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DEFAULTVALUE_FIELD_NUMBER: builtins.int
    VALIDATOR_FIELD_NUMBER: builtins.int
    name: typing.Text
    type: typing.Text
    defaultValue: typing.Text
    validator: typing.Text
    """	name additional business validator"""

    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        type: typing.Optional[typing.Text] = ...,
        defaultValue: typing.Optional[typing.Text] = ...,
        validator: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["defaultValue",b"defaultValue","name",b"name","type",b"type","validator",b"validator"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["defaultValue",b"defaultValue","name",b"name","type",b"type","validator",b"validator"]) -> None: ...
global___OrderPropertyDefinition = OrderPropertyDefinition

class OrderTypeDefinition(google.protobuf.message.Message):
    """The order type definition specifies one order type with all appropriate additional possible settings"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORDERTYPE_FIELD_NUMBER: builtins.int
    DISPLAYNAME_FIELD_NUMBER: builtins.int
    ACCOUNTS_FIELD_NUMBER: builtins.int
    DESTINATIONRULE_FIELD_NUMBER: builtins.int
    RESTRICTIONS_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    orderType: typing.Text
    """	order type that is set in the order"""

    displayName: typing.Text
    """	will be displayed on the button"""

    accounts: typing.Text
    """	comma separated list of selectable accounts"""

    destinationRule: typing.Text
    """	allows customization of the destinations"""

    restrictions: builtins.int
    """	flags that control the order fields and behavior"""

    flags: typing.Text
    """	order flags"""

    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OrderPropertyDefinition]:
        """	addition order data in the form of a property bag"""
        pass
    def __init__(self,
        *,
        orderType: typing.Optional[typing.Text] = ...,
        displayName: typing.Optional[typing.Text] = ...,
        accounts: typing.Optional[typing.Text] = ...,
        destinationRule: typing.Optional[typing.Text] = ...,
        restrictions: typing.Optional[builtins.int] = ...,
        flags: typing.Optional[typing.Text] = ...,
        properties: typing.Optional[typing.Iterable[global___OrderPropertyDefinition]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["accounts",b"accounts","destinationRule",b"destinationRule","displayName",b"displayName","flags",b"flags","orderType",b"orderType","restrictions",b"restrictions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["accounts",b"accounts","destinationRule",b"destinationRule","displayName",b"displayName","flags",b"flags","orderType",b"orderType","properties",b"properties","restrictions",b"restrictions"]) -> None: ...
global___OrderTypeDefinition = OrderTypeDefinition

class DirectActionDefinition(google.protobuf.message.Message):
    """Definition for Direct Action configuration"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ALGONAME_FIELD_NUMBER: builtins.int
    INPUTVALUES_FIELD_NUMBER: builtins.int
    ADDITIONALINSTRUMENTS_FIELD_NUMBER: builtins.int
    algoName: typing.Text
    """	name of the Algo"""

    @property
    def inputValues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.Property]:
        """	input values"""
        pass
    @property
    def additionalInstruments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActAlgo_pb2.NamedInstrument]:
        """	additional instruments"""
        pass
    def __init__(self,
        *,
        algoName: typing.Optional[typing.Text] = ...,
        inputValues: typing.Optional[typing.Iterable[ActTypes_pb2.Property]] = ...,
        additionalInstruments: typing.Optional[typing.Iterable[ActAlgo_pb2.NamedInstrument]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["algoName",b"algoName"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["additionalInstruments",b"additionalInstruments","algoName",b"algoName","inputValues",b"inputValues"]) -> None: ...
global___DirectActionDefinition = DirectActionDefinition

class Destination(google.protobuf.message.Message):
    """A destination specifies an exchange and a route (broker) through which it is reached"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ROUTE_FIELD_NUMBER: builtins.int
    EXCHANGE_FIELD_NUMBER: builtins.int
    DISPLAYNAME_FIELD_NUMBER: builtins.int
    ORDERTYPES_FIELD_NUMBER: builtins.int
    BUSINESSORDERTYPES_FIELD_NUMBER: builtins.int
    route: typing.Text
    """	broker name or blank/empty for native connections"""

    exchange: typing.Text
    """	MIC"""

    displayName: typing.Text
    """	exchange name displayed in the combo box"""

    @property
    def orderTypes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OrderTypeDefinition]:
        """	order types with their metadata"""
        pass
    businessOrderTypes: typing.Text
    """	business order type for the given exchange"""

    def __init__(self,
        *,
        route: typing.Optional[typing.Text] = ...,
        exchange: typing.Optional[typing.Text] = ...,
        displayName: typing.Optional[typing.Text] = ...,
        orderTypes: typing.Optional[typing.Iterable[global___OrderTypeDefinition]] = ...,
        businessOrderTypes: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["businessOrderTypes",b"businessOrderTypes","displayName",b"displayName","exchange",b"exchange","route",b"route"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["businessOrderTypes",b"businessOrderTypes","displayName",b"displayName","exchange",b"exchange","orderTypes",b"orderTypes","route",b"route"]) -> None: ...
global___Destination = Destination

class OrderData(google.protobuf.message.Message):
    """The order data contains the complete order data and is used for broadcasts"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    ORDERKEY_FIELD_NUMBER: builtins.int
    OLDIID_FIELD_NUMBER: builtins.int
    ORDERSTATUS_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SCALEDQUANTITY_FIELD_NUMBER: builtins.int
    DECQUANTITY_FIELD_NUMBER: builtins.int
    SCALEDACTIVEQUANTITY_FIELD_NUMBER: builtins.int
    DECACTIVEQUANTITY_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    ORDERTYPE_FIELD_NUMBER: builtins.int
    DESTINATION_FIELD_NUMBER: builtins.int
    ROUTE_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    FREEFORM_FIELD_NUMBER: builtins.int
    OPENCLOSE_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    COUNTERPART_FIELD_NUMBER: builtins.int
    CREATOR_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    orderKey: typing.Text
    oldIId: typing.Text
    orderStatus: typing.Text
    price: builtins.int
    scaledQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decQuantity: builtins.int
    """	quantity with decimals"""

    scaledActiveQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decActiveQuantity: builtins.int
    """	quantity with decimals"""

    side: typing.Text
    orderType: typing.Text
    destination: typing.Text
    """	MIC if destination isn't local to the market in instrument"""

    route: typing.Text
    """	Route to which the order should be sent (native or execution vendor)"""

    account: typing.Text
    freeForm: typing.Text
    openClose: typing.Text
    """	"Open"/"Close" """

    flags: typing.Text
    """	order flags"""

    expiration: typing.Text
    """	YYYYMMDD"""

    counterpart: typing.Text
    creator: typing.Text
    """	automation controlling the order"""

    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ActTypes_pb2.Property]: ...
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        orderKey: typing.Optional[typing.Text] = ...,
        oldIId: typing.Optional[typing.Text] = ...,
        orderStatus: typing.Optional[typing.Text] = ...,
        price: typing.Optional[builtins.int] = ...,
        scaledQuantity: typing.Optional[builtins.int] = ...,
        decQuantity: typing.Optional[builtins.int] = ...,
        scaledActiveQuantity: typing.Optional[builtins.int] = ...,
        decActiveQuantity: typing.Optional[builtins.int] = ...,
        side: typing.Optional[typing.Text] = ...,
        orderType: typing.Optional[typing.Text] = ...,
        destination: typing.Optional[typing.Text] = ...,
        route: typing.Optional[typing.Text] = ...,
        account: typing.Optional[typing.Text] = ...,
        freeForm: typing.Optional[typing.Text] = ...,
        openClose: typing.Optional[typing.Text] = ...,
        flags: typing.Optional[typing.Text] = ...,
        expiration: typing.Optional[typing.Text] = ...,
        counterpart: typing.Optional[typing.Text] = ...,
        creator: typing.Optional[typing.Text] = ...,
        properties: typing.Optional[typing.Iterable[ActTypes_pb2.Property]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account",b"account","counterpart",b"counterpart","creator",b"creator","decActiveQuantity",b"decActiveQuantity","decQuantity",b"decQuantity","destination",b"destination","expiration",b"expiration","flags",b"flags","freeForm",b"freeForm","instrument",b"instrument","oldIId",b"oldIId","openClose",b"openClose","orderKey",b"orderKey","orderStatus",b"orderStatus","orderType",b"orderType","price",b"price","route",b"route","scaledActiveQuantity",b"scaledActiveQuantity","scaledQuantity",b"scaledQuantity","side",b"side"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account",b"account","counterpart",b"counterpart","creator",b"creator","decActiveQuantity",b"decActiveQuantity","decQuantity",b"decQuantity","destination",b"destination","expiration",b"expiration","flags",b"flags","freeForm",b"freeForm","instrument",b"instrument","oldIId",b"oldIId","openClose",b"openClose","orderKey",b"orderKey","orderStatus",b"orderStatus","orderType",b"orderType","price",b"price","properties",b"properties","route",b"route","scaledActiveQuantity",b"scaledActiveQuantity","scaledQuantity",b"scaledQuantity","side",b"side"]) -> None: ...
global___OrderData = OrderData

class OrderMetadata(google.protobuf.message.Message):
    """The order metadata contains all information to create an order editor dialog that supports
    editing all known types of orders for all configurations
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    DESTINATIONS_FIELD_NUMBER: builtins.int
    ORDERDEFAULTVALUES_FIELD_NUMBER: builtins.int
    ALLOCATION_FIELD_NUMBER: builtins.int
    SUPPORTRFQ_FIELD_NUMBER: builtins.int
    SUPPORTRFC_FIELD_NUMBER: builtins.int
    DUALQUANTITY_FIELD_NUMBER: builtins.int
    SPINQUANTITY_FIELD_NUMBER: builtins.int
    DIRECTACTIONS_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    @property
    def destinations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Destination]: ...
    @property
    def orderDefaultValues(self) -> global___OrderData:
        """	the default values to initialize the order editor"""
        pass
    @property
    def allocation(self) -> ActPort_pb2.PortfolioAllocation:
        """	information for allocation menu (empty if multi account not set)"""
        pass
    supportRFQ: builtins.bool
    """deprecated field number 5
    	enable the RFQ button in the order editor
    """

    supportRFC: builtins.bool
    """	enable the RFC button in the order editor"""

    dualQuantity: typing.Text
    """	currencies for dual quantity editing, exchange rate and precision (e.g. "USD,BTC,,4")"""

    spinQuantity: builtins.int
    """	step size for order editor quantity inc/dec"""

    @property
    def directActions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DirectActionDefinition]:
        """	metadata for direct actions that can be started from the order editor"""
        pass
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        destinations: typing.Optional[typing.Iterable[global___Destination]] = ...,
        orderDefaultValues: typing.Optional[global___OrderData] = ...,
        allocation: typing.Optional[ActPort_pb2.PortfolioAllocation] = ...,
        supportRFQ: typing.Optional[builtins.bool] = ...,
        supportRFC: typing.Optional[builtins.bool] = ...,
        dualQuantity: typing.Optional[typing.Text] = ...,
        spinQuantity: typing.Optional[builtins.int] = ...,
        directActions: typing.Optional[typing.Iterable[global___DirectActionDefinition]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["allocation",b"allocation","dualQuantity",b"dualQuantity","instrument",b"instrument","orderDefaultValues",b"orderDefaultValues","spinQuantity",b"spinQuantity","supportRFC",b"supportRFC","supportRFQ",b"supportRFQ"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["allocation",b"allocation","destinations",b"destinations","directActions",b"directActions","dualQuantity",b"dualQuantity","instrument",b"instrument","orderDefaultValues",b"orderDefaultValues","spinQuantity",b"spinQuantity","supportRFC",b"supportRFC","supportRFQ",b"supportRFQ"]) -> None: ...
global___OrderMetadata = OrderMetadata

class OrderLimits(google.protobuf.message.Message):
    """	all quantities are passed as scaled and quantity with decimals for now, the quantity with decimals always has priority"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRODUCT_FIELD_NUMBER: builtins.int
    SCALEDMAXORDERQUANTITY_FIELD_NUMBER: builtins.int
    DECMAXORDERQUANTITY_FIELD_NUMBER: builtins.int
    SCALEDMAXQUOTEQUANTITY_FIELD_NUMBER: builtins.int
    DECMAXQUOTEQUANTITY_FIELD_NUMBER: builtins.int
    FREEFORM_FIELD_NUMBER: builtins.int
    LENDINGBROKER_FIELD_NUMBER: builtins.int
    SCALEDMAXMARKETQUANTITY_FIELD_NUMBER: builtins.int
    DECMAXMARKETQUANTITY_FIELD_NUMBER: builtins.int
    SCALEDQUANTITYINCDEC_FIELD_NUMBER: builtins.int
    DECQUANTITYINCDEC_FIELD_NUMBER: builtins.int
    SCALEDBBOCLICKQUANTITY_FIELD_NUMBER: builtins.int
    DECBBOCLICKQUANTITY_FIELD_NUMBER: builtins.int
    SCALEDNBBOCLICKQUANTITY_FIELD_NUMBER: builtins.int
    DECNBBOCLICKQUANTITY_FIELD_NUMBER: builtins.int
    ORDERPRICESAFETY_FIELD_NUMBER: builtins.int
    ABSOLUTEPRICELIMITS_FIELD_NUMBER: builtins.int
    product: typing.Text
    scaledMaxOrderQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decMaxOrderQuantity: builtins.int
    scaledMaxQuoteQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decMaxQuoteQuantity: builtins.int
    freeForm: typing.Text
    lendingBroker: typing.Text
    scaledMaxMarketQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decMaxMarketQuantity: builtins.int
    scaledQuantityIncDec: builtins.int
    """	scaled quantity, will be deprecated"""

    decQuantityIncDec: builtins.int
    scaledBBOClickQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decBBOClickQuantity: builtins.int
    scaledNBBOClickQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decNBBOClickQuantity: builtins.int
    @property
    def orderPriceSafety(self) -> ActTypes_pb2.PercentLimit: ...
    @property
    def absolutePriceLimits(self) -> ActTypes_pb2.AbsoluteLimit: ...
    def __init__(self,
        *,
        product: typing.Optional[typing.Text] = ...,
        scaledMaxOrderQuantity: typing.Optional[builtins.int] = ...,
        decMaxOrderQuantity: typing.Optional[builtins.int] = ...,
        scaledMaxQuoteQuantity: typing.Optional[builtins.int] = ...,
        decMaxQuoteQuantity: typing.Optional[builtins.int] = ...,
        freeForm: typing.Optional[typing.Text] = ...,
        lendingBroker: typing.Optional[typing.Text] = ...,
        scaledMaxMarketQuantity: typing.Optional[builtins.int] = ...,
        decMaxMarketQuantity: typing.Optional[builtins.int] = ...,
        scaledQuantityIncDec: typing.Optional[builtins.int] = ...,
        decQuantityIncDec: typing.Optional[builtins.int] = ...,
        scaledBBOClickQuantity: typing.Optional[builtins.int] = ...,
        decBBOClickQuantity: typing.Optional[builtins.int] = ...,
        scaledNBBOClickQuantity: typing.Optional[builtins.int] = ...,
        decNBBOClickQuantity: typing.Optional[builtins.int] = ...,
        orderPriceSafety: typing.Optional[ActTypes_pb2.PercentLimit] = ...,
        absolutePriceLimits: typing.Optional[ActTypes_pb2.AbsoluteLimit] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["absolutePriceLimits",b"absolutePriceLimits","decBBOClickQuantity",b"decBBOClickQuantity","decMaxMarketQuantity",b"decMaxMarketQuantity","decMaxOrderQuantity",b"decMaxOrderQuantity","decMaxQuoteQuantity",b"decMaxQuoteQuantity","decNBBOClickQuantity",b"decNBBOClickQuantity","decQuantityIncDec",b"decQuantityIncDec","freeForm",b"freeForm","lendingBroker",b"lendingBroker","orderPriceSafety",b"orderPriceSafety","product",b"product","scaledBBOClickQuantity",b"scaledBBOClickQuantity","scaledMaxMarketQuantity",b"scaledMaxMarketQuantity","scaledMaxOrderQuantity",b"scaledMaxOrderQuantity","scaledMaxQuoteQuantity",b"scaledMaxQuoteQuantity","scaledNBBOClickQuantity",b"scaledNBBOClickQuantity","scaledQuantityIncDec",b"scaledQuantityIncDec"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["absolutePriceLimits",b"absolutePriceLimits","decBBOClickQuantity",b"decBBOClickQuantity","decMaxMarketQuantity",b"decMaxMarketQuantity","decMaxOrderQuantity",b"decMaxOrderQuantity","decMaxQuoteQuantity",b"decMaxQuoteQuantity","decNBBOClickQuantity",b"decNBBOClickQuantity","decQuantityIncDec",b"decQuantityIncDec","freeForm",b"freeForm","lendingBroker",b"lendingBroker","orderPriceSafety",b"orderPriceSafety","product",b"product","scaledBBOClickQuantity",b"scaledBBOClickQuantity","scaledMaxMarketQuantity",b"scaledMaxMarketQuantity","scaledMaxOrderQuantity",b"scaledMaxOrderQuantity","scaledMaxQuoteQuantity",b"scaledMaxQuoteQuantity","scaledNBBOClickQuantity",b"scaledNBBOClickQuantity","scaledQuantityIncDec",b"scaledQuantityIncDec"]) -> None: ...
global___OrderLimits = OrderLimits

class Request(google.protobuf.message.Message):
    """Requests are passed from client system and will contain only one of the specific requests
    At the moment we support Add, Update and Delete request messages
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    ADDORDER_FIELD_NUMBER: builtins.int
    UPDATEORDER_FIELD_NUMBER: builtins.int
    DELETEORDER_FIELD_NUMBER: builtins.int
    METADATAREQUEST_FIELD_NUMBER: builtins.int
    ORDERKEY_FIELD_NUMBER: builtins.int
    MARKETEVENTTYPE_FIELD_NUMBER: builtins.int
    LIMITSDEFINITIONS_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    @property
    def addOrder(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AddOrder]: ...
    @property
    def updateOrder(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UpdateOrder]: ...
    @property
    def deleteOrder(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeleteOrder]: ...
    @property
    def metadataRequest(self) -> global___MetadataRequest: ...
    orderKey: typing.Text
    """	used for order subscription, can be combined with metadata request"""

    marketEventType: typing.Text
    """	"BestMan" will retrieve the best manual order
    	currently supported: "RFQ", "RFC"
    """

    @property
    def limitsDefinitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OrderLimits]: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        addOrder: typing.Optional[typing.Iterable[global___AddOrder]] = ...,
        updateOrder: typing.Optional[typing.Iterable[global___UpdateOrder]] = ...,
        deleteOrder: typing.Optional[typing.Iterable[global___DeleteOrder]] = ...,
        metadataRequest: typing.Optional[global___MetadataRequest] = ...,
        orderKey: typing.Optional[typing.Text] = ...,
        marketEventType: typing.Optional[typing.Text] = ...,
        limitsDefinitions: typing.Optional[typing.Iterable[global___OrderLimits]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","marketEventType",b"marketEventType","metadataRequest",b"metadataRequest","orderKey",b"orderKey","requestType",b"requestType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addOrder",b"addOrder","clientId",b"clientId","deleteOrder",b"deleteOrder","limitsDefinitions",b"limitsDefinitions","marketEventType",b"marketEventType","metadataRequest",b"metadataRequest","orderKey",b"orderKey","requestType",b"requestType","updateOrder",b"updateOrder"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Responses are passed from actant system and will contain only one of the specific responses.
    At the moment we support Add, Update and Delete response messages
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    ORDEROPERATIONRESULT_FIELD_NUMBER: builtins.int
    ORDERMETADATA_FIELD_NUMBER: builtins.int
    ORDERDATA_FIELD_NUMBER: builtins.int
    LIMITSDEFINITIONS_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    @property
    def orderOperationResult(self) -> global___OrderOperationResult: ...
    @property
    def orderMetadata(self) -> global___OrderMetadata: ...
    @property
    def orderData(self) -> global___OrderData:
        """	used for subscriptions"""
        pass
    @property
    def limitsDefinitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OrderLimits]: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        orderOperationResult: typing.Optional[global___OrderOperationResult] = ...,
        orderMetadata: typing.Optional[global___OrderMetadata] = ...,
        orderData: typing.Optional[global___OrderData] = ...,
        limitsDefinitions: typing.Optional[typing.Iterable[global___OrderLimits]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","orderData",b"orderData","orderMetadata",b"orderMetadata","orderOperationResult",b"orderOperationResult","responseType",b"responseType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","limitsDefinitions",b"limitsDefinitions","operationStatus",b"operationStatus","orderData",b"orderData","orderMetadata",b"orderMetadata","orderOperationResult",b"orderOperationResult","responseType",b"responseType"]) -> None: ...
global___Response = Response
