# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActPort.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rActPort.proto\x12\x07\x41\x63tPort\"J\n\nAllocation\x12\x13\n\x0b\x64isplayName\x18\x01 \x01(\t\x12\x15\n\rportfolioName\x18\x02 \x01(\t\x12\x10\n\x08products\x18\x03 \x03(\t\"w\n\x13PortfolioAllocation\x12\x19\n\x11underlyingProduct\x18\x01 \x01(\t\x12\x1b\n\x13\x61utomationPortfolio\x18\x02 \x01(\t\x12(\n\x0b\x61llocations\x18\x03 \x03(\x0b\x32\x13.ActPort.Allocation')



_ALLOCATION = DESCRIPTOR.message_types_by_name['Allocation']
_PORTFOLIOALLOCATION = DESCRIPTOR.message_types_by_name['PortfolioAllocation']
Allocation = _reflection.GeneratedProtocolMessageType('Allocation', (_message.Message,), {
  'DESCRIPTOR' : _ALLOCATION,
  '__module__' : 'ActPort_pb2'
  # @@protoc_insertion_point(class_scope:ActPort.Allocation)
  })
_sym_db.RegisterMessage(Allocation)

PortfolioAllocation = _reflection.GeneratedProtocolMessageType('PortfolioAllocation', (_message.Message,), {
  'DESCRIPTOR' : _PORTFOLIOALLOCATION,
  '__module__' : 'ActPort_pb2'
  # @@protoc_insertion_point(class_scope:ActPort.PortfolioAllocation)
  })
_sym_db.RegisterMessage(PortfolioAllocation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALLOCATION._serialized_start=26
  _ALLOCATION._serialized_end=100
  _PORTFOLIOALLOCATION._serialized_start=102
  _PORTFOLIOALLOCATION._serialized_end=221
# @@protoc_insertion_point(module_scope)
