"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActTypes_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Creatability:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _CreatabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Creatability.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STRATEGY_NOT_CREATABLE: _Creatability.ValueType  # 0
    STRATEGY_CREATABLE: _Creatability.ValueType  # 1
    STRATEGY_CREATED: _Creatability.ValueType  # 2
class Creatability(_Creatability, metaclass=_CreatabilityEnumTypeWrapper):
    pass

STRATEGY_NOT_CREATABLE: Creatability.ValueType  # 0
STRATEGY_CREATABLE: Creatability.ValueType  # 1
STRATEGY_CREATED: Creatability.ValueType  # 2
global___Creatability = Creatability


class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_IDENTIFY_STRATEGY: _RequestType.ValueType  # 0
    REQ_CREATE_STRATEGY: _RequestType.ValueType  # 1
    REQ_SAVE_STRATEGY: _RequestType.ValueType  # 5
class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    """Request messages are passed from client->actant and are identified by RequestType enum"""
    pass

REQ_IDENTIFY_STRATEGY: RequestType.ValueType  # 0
REQ_CREATE_STRATEGY: RequestType.ValueType  # 1
REQ_SAVE_STRATEGY: RequestType.ValueType  # 5
global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_IDENTIFY_STRATEGY: _ResponseType.ValueType  # 0
    RESP_CREATE_STRATEGY: _ResponseType.ValueType  # 1
    RESP_SAVE_STRATEGY: _ResponseType.ValueType  # 5
class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    """Response messages are passed from actant->client and are identified by ResponseType enum"""
    pass

RESP_IDENTIFY_STRATEGY: ResponseType.ValueType  # 0
RESP_CREATE_STRATEGY: ResponseType.ValueType  # 1
RESP_SAVE_STRATEGY: ResponseType.ValueType  # 5
global___ResponseType = ResponseType


class StrategyLeg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    LEGQUANTITY_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    price: builtins.int
    """	URef for stock/future, Manual UPrice for options"""

    legQuantity: builtins.int
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        price: typing.Optional[builtins.int] = ...,
        legQuantity: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["instrument",b"instrument","legQuantity",b"legQuantity","price",b"price"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["instrument",b"instrument","legQuantity",b"legQuantity","price",b"price"]) -> None: ...
global___StrategyLeg = StrategyLeg

class StrategyComposition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LEGS_FIELD_NUMBER: builtins.int
    RATIOSCALING_FIELD_NUMBER: builtins.int
    @property
    def legs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StrategyLeg]: ...
    RatioScaling: builtins.int
    def __init__(self,
        *,
        legs: typing.Optional[typing.Iterable[global___StrategyLeg]] = ...,
        RatioScaling: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["RatioScaling",b"RatioScaling"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["RatioScaling",b"RatioScaling","legs",b"legs"]) -> None: ...
global___StrategyComposition = StrategyComposition

class StrategyQuotes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OWNBBO_FIELD_NUMBER: builtins.int
    BROKERBBO_FIELD_NUMBER: builtins.int
    NOTES_FIELD_NUMBER: builtins.int
    @property
    def ownBBO(self) -> ActTypes_pb2.ScaledBBO:
        """	for backwards compatibility reasons the strategy protocol continues"""
        pass
    @property
    def brokerBBO(self) -> ActTypes_pb2.ScaledBBO:
        """	to use scaled quantities in the OTC Watch server"""
        pass
    notes: typing.Text
    def __init__(self,
        *,
        ownBBO: typing.Optional[ActTypes_pb2.ScaledBBO] = ...,
        brokerBBO: typing.Optional[ActTypes_pb2.ScaledBBO] = ...,
        notes: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["brokerBBO",b"brokerBBO","notes",b"notes","ownBBO",b"ownBBO"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["brokerBBO",b"brokerBBO","notes",b"notes","ownBBO",b"ownBBO"]) -> None: ...
global___StrategyQuotes = StrategyQuotes

class StrategyIdentification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CREATABILITY_FIELD_NUMBER: builtins.int
    STRATEGYTYPENAME_FIELD_NUMBER: builtins.int
    STRATEGYINSTRUMENT_FIELD_NUMBER: builtins.int
    SUPPORTRFQ_FIELD_NUMBER: builtins.int
    creatability: global___Creatability.ValueType
    strategyTypeName: typing.Text
    strategyInstrument: typing.Text
    supportRFQ: builtins.bool
    def __init__(self,
        *,
        creatability: typing.Optional[global___Creatability.ValueType] = ...,
        strategyTypeName: typing.Optional[typing.Text] = ...,
        strategyInstrument: typing.Optional[typing.Text] = ...,
        supportRFQ: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["creatability",b"creatability","strategyInstrument",b"strategyInstrument","strategyTypeName",b"strategyTypeName","supportRFQ",b"supportRFQ"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["creatability",b"creatability","strategyInstrument",b"strategyInstrument","strategyTypeName",b"strategyTypeName","supportRFQ",b"supportRFQ"]) -> None: ...
global___StrategyIdentification = StrategyIdentification

class Request(google.protobuf.message.Message):
    """Requests are passed from client system and will contain only one of the specific requests"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    STRATEGYINSTRUMENT_FIELD_NUMBER: builtins.int
    STRATEGYQUOTES_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    @property
    def strategy(self) -> global___StrategyComposition: ...
    uuid: typing.Text
    StrategyInstrument: typing.Text
    @property
    def strategyQuotes(self) -> global___StrategyQuotes: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        strategy: typing.Optional[global___StrategyComposition] = ...,
        uuid: typing.Optional[typing.Text] = ...,
        StrategyInstrument: typing.Optional[typing.Text] = ...,
        strategyQuotes: typing.Optional[global___StrategyQuotes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["StrategyInstrument",b"StrategyInstrument","clientId",b"clientId","requestType",b"requestType","strategy",b"strategy","strategyQuotes",b"strategyQuotes","uuid",b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["StrategyInstrument",b"StrategyInstrument","clientId",b"clientId","requestType",b"requestType","strategy",b"strategy","strategyQuotes",b"strategyQuotes","uuid",b"uuid"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Responses are passed from actant system and will contain only one of the specific responses."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    STRATEGYIDENTIFICATION_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    STRATEGYQUOTES_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    @property
    def strategyIdentification(self) -> global___StrategyIdentification: ...
    @property
    def strategy(self) -> global___StrategyComposition: ...
    @property
    def strategyQuotes(self) -> global___StrategyQuotes: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        strategyIdentification: typing.Optional[global___StrategyIdentification] = ...,
        strategy: typing.Optional[global___StrategyComposition] = ...,
        strategyQuotes: typing.Optional[global___StrategyQuotes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType","strategy",b"strategy","strategyIdentification",b"strategyIdentification","strategyQuotes",b"strategyQuotes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType","strategy",b"strategy","strategyIdentification",b"strategyIdentification","strategyQuotes",b"strategyQuotes"]) -> None: ...
global___Response = Response
