"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActTypes_pb2
from . import DataExchangeAPI_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_SUBSCRIBE_TICKS: _RequestType.ValueType  # 0
    REQ_UNSUBSCRIBE_TICKS: _RequestType.ValueType  # 1
class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    """Request messages are passed from client->actant and are identified by RequestType enum"""
    pass

REQ_SUBSCRIBE_TICKS: RequestType.ValueType  # 0
REQ_UNSUBSCRIBE_TICKS: RequestType.ValueType  # 1
global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_SUBSCRIBE_TICKS: _ResponseType.ValueType  # 0
    RESP_UNSUBSCRIBE_TICKS: _ResponseType.ValueType  # 1
    MSG_TICKS_UPDATE: _ResponseType.ValueType  # 2000
    """	broadcast messages"""

    MSG_TICKS_INIUPDATE: _ResponseType.ValueType  # 2001
class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    """Response messages are passed from actant->client and are identified by ResponseType enum"""
    pass

RESP_SUBSCRIBE_TICKS: ResponseType.ValueType  # 0
RESP_UNSUBSCRIBE_TICKS: ResponseType.ValueType  # 1
MSG_TICKS_UPDATE: ResponseType.ValueType  # 2000
"""	broadcast messages"""

MSG_TICKS_INIUPDATE: ResponseType.ValueType  # 2001
global___ResponseType = ResponseType


class TickData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTRUMENT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SCALEDQUANTITY_FIELD_NUMBER: builtins.int
    DECQUANTITY_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    PRICESOURCE_FIELD_NUMBER: builtins.int
    AGGRESSOR_FIELD_NUMBER: builtins.int
    MARKETUSER_FIELD_NUMBER: builtins.int
    DEXVALUES_FIELD_NUMBER: builtins.int
    instrument: typing.Text
    timestamp: builtins.float
    """	tick count"""

    price: builtins.int
    scaledQuantity: builtins.int
    """	scaled quantity, will be deprecated"""

    decQuantity: builtins.int
    """	quantity with decimals"""

    side: typing.Text
    priceSource: typing.Text
    aggressor: typing.Text
    marketUser: typing.Text
    @property
    def dexValues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[DataExchangeAPI_pb2.VariantValue]: ...
    def __init__(self,
        *,
        instrument: typing.Optional[typing.Text] = ...,
        timestamp: typing.Optional[builtins.float] = ...,
        price: typing.Optional[builtins.int] = ...,
        scaledQuantity: typing.Optional[builtins.int] = ...,
        decQuantity: typing.Optional[builtins.int] = ...,
        side: typing.Optional[typing.Text] = ...,
        priceSource: typing.Optional[typing.Text] = ...,
        aggressor: typing.Optional[typing.Text] = ...,
        marketUser: typing.Optional[typing.Text] = ...,
        dexValues: typing.Optional[typing.Iterable[DataExchangeAPI_pb2.VariantValue]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["aggressor",b"aggressor","decQuantity",b"decQuantity","instrument",b"instrument","marketUser",b"marketUser","price",b"price","priceSource",b"priceSource","scaledQuantity",b"scaledQuantity","side",b"side","timestamp",b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aggressor",b"aggressor","decQuantity",b"decQuantity","dexValues",b"dexValues","instrument",b"instrument","marketUser",b"marketUser","price",b"price","priceSource",b"priceSource","scaledQuantity",b"scaledQuantity","side",b"side","timestamp",b"timestamp"]) -> None: ...
global___TickData = TickData

class Request(google.protobuf.message.Message):
    """Requests are passed from client system and will contain only one of the specific requests"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    PRODUCTS_FIELD_NUMBER: builtins.int
    DEXCOLUMNS_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    @property
    def products(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def dexColumns(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        products: typing.Optional[typing.Iterable[typing.Text]] = ...,
        dexColumns: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","requestType",b"requestType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","dexColumns",b"dexColumns","products",b"products","requestType",b"requestType"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Responses are passed from actant system and will contain only one of the specific responses."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    TICKS_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    @property
    def ticks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TickData]: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        ticks: typing.Optional[typing.Iterable[global___TickData]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType","ticks",b"ticks"]) -> None: ...
global___Response = Response
