# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActTypes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x41\x63tTypes.proto\x12\x06\x41\x63tAPI\"A\n\x0fOperationStatus\x12\x14\n\x0c\x65rrorMessage\x18\x01 \x01(\t\x12\x18\n\x10\x65rrorStatusFlags\x18\x02 \x01(\r\"\'\n\x08Property\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"-\n\x0e\x44oubleProperty\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"M\n\tScaledBBO\x12\x12\n\nscaledNBid\x18\x01 \x01(\r\x12\x0b\n\x03\x42id\x18\x02 \x01(\x12\x12\x0b\n\x03\x41sk\x18\x03 \x01(\x12\x12\x12\n\nscaledNAsk\x18\x04 \x01(\r\"9\n\x08UniqueId\x12\n\n\x02id\x18\x01 \x01(\r\x12\x13\n\x0b\x63hangeCount\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\"1\n\rAbsoluteLimit\x12\x0f\n\x07minimum\x18\x01 \x01(\x01\x12\x0f\n\x07maximum\x18\x02 \x01(\x01\"D\n\x0cPercentLimit\x12\x12\n\npercentage\x18\x01 \x01(\x01\x12\x0f\n\x07minimum\x18\x02 \x01(\x01\x12\x0f\n\x07maximum\x18\x03 \x01(\x01')



_OPERATIONSTATUS = DESCRIPTOR.message_types_by_name['OperationStatus']
_PROPERTY = DESCRIPTOR.message_types_by_name['Property']
_DOUBLEPROPERTY = DESCRIPTOR.message_types_by_name['DoubleProperty']
_SCALEDBBO = DESCRIPTOR.message_types_by_name['ScaledBBO']
_UNIQUEID = DESCRIPTOR.message_types_by_name['UniqueId']
_ABSOLUTELIMIT = DESCRIPTOR.message_types_by_name['AbsoluteLimit']
_PERCENTLIMIT = DESCRIPTOR.message_types_by_name['PercentLimit']
OperationStatus = _reflection.GeneratedProtocolMessageType('OperationStatus', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONSTATUS,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.OperationStatus)
  })
_sym_db.RegisterMessage(OperationStatus)

Property = _reflection.GeneratedProtocolMessageType('Property', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTY,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.Property)
  })
_sym_db.RegisterMessage(Property)

DoubleProperty = _reflection.GeneratedProtocolMessageType('DoubleProperty', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEPROPERTY,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.DoubleProperty)
  })
_sym_db.RegisterMessage(DoubleProperty)

ScaledBBO = _reflection.GeneratedProtocolMessageType('ScaledBBO', (_message.Message,), {
  'DESCRIPTOR' : _SCALEDBBO,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.ScaledBBO)
  })
_sym_db.RegisterMessage(ScaledBBO)

UniqueId = _reflection.GeneratedProtocolMessageType('UniqueId', (_message.Message,), {
  'DESCRIPTOR' : _UNIQUEID,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.UniqueId)
  })
_sym_db.RegisterMessage(UniqueId)

AbsoluteLimit = _reflection.GeneratedProtocolMessageType('AbsoluteLimit', (_message.Message,), {
  'DESCRIPTOR' : _ABSOLUTELIMIT,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.AbsoluteLimit)
  })
_sym_db.RegisterMessage(AbsoluteLimit)

PercentLimit = _reflection.GeneratedProtocolMessageType('PercentLimit', (_message.Message,), {
  'DESCRIPTOR' : _PERCENTLIMIT,
  '__module__' : 'ActTypes_pb2'
  # @@protoc_insertion_point(class_scope:ActAPI.PercentLimit)
  })
_sym_db.RegisterMessage(PercentLimit)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATIONSTATUS._serialized_start=26
  _OPERATIONSTATUS._serialized_end=91
  _PROPERTY._serialized_start=93
  _PROPERTY._serialized_end=132
  _DOUBLEPROPERTY._serialized_start=134
  _DOUBLEPROPERTY._serialized_end=179
  _SCALEDBBO._serialized_start=181
  _SCALEDBBO._serialized_end=258
  _UNIQUEID._serialized_start=260
  _UNIQUEID._serialized_end=317
  _ABSOLUTELIMIT._serialized_start=319
  _ABSOLUTELIMIT._serialized_end=368
  _PERCENTLIMIT._serialized_start=370
  _PERCENTLIMIT._serialized_end=438
# @@protoc_insertion_point(module_scope)
