# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActTicks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ActTypes_pb2
from . import DataExchangeAPI_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x41\x63tTicks.proto\x12\x08\x41\x63tTicks\x1a\x0e\x41\x63tTypes.proto\x1a\x15\x44\x61taExchangeAPI.proto\"\xe9\x01\n\x08TickData\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\r\n\x05price\x18\x03 \x01(\x12\x12\x16\n\x0escaledQuantity\x18\x04 \x01(\r\x12\x13\n\x0b\x64\x65\x63Quantity\x18\n \x01(\x04\x12\x0c\n\x04side\x18\x05 \x01(\t\x12\x13\n\x0bpriceSource\x18\x06 \x01(\t\x12\x11\n\taggressor\x18\x07 \x01(\t\x12\x12\n\nmarketUser\x18\x08 \x01(\t\x12\x30\n\tdexValues\x18\t \x03(\x0b\x32\x1d.DataExchangeAPI.VariantValue\"m\n\x07Request\x12*\n\x0brequestType\x18\x01 \x01(\x0e\x32\x15.ActTicks.RequestType\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x11\x12\x10\n\x08products\x18\x03 \x03(\t\x12\x12\n\ndexColumns\x18\x04 \x03(\t\"\x9f\x01\n\x08Response\x12,\n\x0cresponseType\x18\x01 \x01(\x0e\x32\x16.ActTicks.ResponseType\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x11\x12\x30\n\x0foperationStatus\x18\x03 \x01(\x0b\x32\x17.ActAPI.OperationStatus\x12!\n\x05ticks\x18\x08 \x03(\x0b\x32\x12.ActTicks.TickData*A\n\x0bRequestType\x12\x17\n\x13REQ_SUBSCRIBE_TICKS\x10\x00\x12\x19\n\x15REQ_UNSUBSCRIBE_TICKS\x10\x01*u\n\x0cResponseType\x12\x18\n\x14RESP_SUBSCRIBE_TICKS\x10\x00\x12\x1a\n\x16RESP_UNSUBSCRIBE_TICKS\x10\x01\x12\x15\n\x10MSG_TICKS_UPDATE\x10\xd0\x0f\x12\x18\n\x13MSG_TICKS_INIUPDATE\x10\xd1\x0f')

_REQUESTTYPE = DESCRIPTOR.enum_types_by_name['RequestType']
RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
_RESPONSETYPE = DESCRIPTOR.enum_types_by_name['ResponseType']
ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
REQ_SUBSCRIBE_TICKS = 0
REQ_UNSUBSCRIBE_TICKS = 1
RESP_SUBSCRIBE_TICKS = 0
RESP_UNSUBSCRIBE_TICKS = 1
MSG_TICKS_UPDATE = 2000
MSG_TICKS_INIUPDATE = 2001


_TICKDATA = DESCRIPTOR.message_types_by_name['TickData']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
TickData = _reflection.GeneratedProtocolMessageType('TickData', (_message.Message,), {
  'DESCRIPTOR' : _TICKDATA,
  '__module__' : 'ActTicks_pb2'
  # @@protoc_insertion_point(class_scope:ActTicks.TickData)
  })
_sym_db.RegisterMessage(TickData)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'ActTicks_pb2'
  # @@protoc_insertion_point(class_scope:ActTicks.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'ActTicks_pb2'
  # @@protoc_insertion_point(class_scope:ActTicks.Response)
  })
_sym_db.RegisterMessage(Response)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTTYPE._serialized_start=576
  _REQUESTTYPE._serialized_end=641
  _RESPONSETYPE._serialized_start=643
  _RESPONSETYPE._serialized_end=760
  _TICKDATA._serialized_start=68
  _TICKDATA._serialized_end=301
  _REQUEST._serialized_start=303
  _REQUEST._serialized_end=412
  _RESPONSE._serialized_start=415
  _RESPONSE._serialized_end=574
# @@protoc_insertion_point(module_scope)
