"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from . import ActTypes_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RequestType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RequestTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RequestType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REQ_SNAPSHOT: _RequestType.ValueType  # 1
    REQ_UPDATE: _RequestType.ValueType  # 2
    REQ_SUBSCRIBE: _RequestType.ValueType  # 3
    REQ_UNSUBSCRIBE: _RequestType.ValueType  # 4
    REQ_SUBSCRIBE_ALL: _RequestType.ValueType  # 5
    REQ_UNSUBSCRIBE_ALL: _RequestType.ValueType  # 6
    REQ_UNDERLYING_LIST_SNAPSHOT: _RequestType.ValueType  # 7
    REQ_UNDERLYING_LIST_SUBSCRIBE: _RequestType.ValueType  # 8
    REQ_UNDERLYING_LIST_UNSUBSCRIBE: _RequestType.ValueType  # 9
class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
    pass

REQ_SNAPSHOT: RequestType.ValueType  # 1
REQ_UPDATE: RequestType.ValueType  # 2
REQ_SUBSCRIBE: RequestType.ValueType  # 3
REQ_UNSUBSCRIBE: RequestType.ValueType  # 4
REQ_SUBSCRIBE_ALL: RequestType.ValueType  # 5
REQ_UNSUBSCRIBE_ALL: RequestType.ValueType  # 6
REQ_UNDERLYING_LIST_SNAPSHOT: RequestType.ValueType  # 7
REQ_UNDERLYING_LIST_SUBSCRIBE: RequestType.ValueType  # 8
REQ_UNDERLYING_LIST_UNSUBSCRIBE: RequestType.ValueType  # 9
global___RequestType = RequestType


class _ResponseType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResponseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESP_SNAPSHOT: _ResponseType.ValueType  # 1
    RESP_UPDATE: _ResponseType.ValueType  # 2
    RESP_SUBSCRIBE: _ResponseType.ValueType  # 3
    RESP_UNSUBSCRIBE: _ResponseType.ValueType  # 4
    RESP_SUBSCRIBE_ALL: _ResponseType.ValueType  # 5
    RESP_UNSUBSCRIBE_ALL: _ResponseType.ValueType  # 6
    RESP_UNDERLYING_LIST_SNAPSHOT: _ResponseType.ValueType  # 7
    RESP_UNDERLYING_LIST_UPDATE: _ResponseType.ValueType  # 8
    RESP_UNDERLYING_LIST_SUBSCRIBE: _ResponseType.ValueType  # 9
    RESP_UNDERLYING_LIST_UNSUBSCRIBE: _ResponseType.ValueType  # 10
class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper):
    pass

RESP_SNAPSHOT: ResponseType.ValueType  # 1
RESP_UPDATE: ResponseType.ValueType  # 2
RESP_SUBSCRIBE: ResponseType.ValueType  # 3
RESP_UNSUBSCRIBE: ResponseType.ValueType  # 4
RESP_SUBSCRIBE_ALL: ResponseType.ValueType  # 5
RESP_UNSUBSCRIBE_ALL: ResponseType.ValueType  # 6
RESP_UNDERLYING_LIST_SNAPSHOT: ResponseType.ValueType  # 7
RESP_UNDERLYING_LIST_UPDATE: ResponseType.ValueType  # 8
RESP_UNDERLYING_LIST_SUBSCRIBE: ResponseType.ValueType  # 9
RESP_UNDERLYING_LIST_UNSUBSCRIBE: ResponseType.ValueType  # 10
global___ResponseType = ResponseType


class _UnderlyingSourceType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _UnderlyingSourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UnderlyingSourceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNDERLYINGSOURCE_UNKNOWN: _UnderlyingSourceType.ValueType  # 0
    UNDERLYINGSOURCE_TRUESPOT: _UnderlyingSourceType.ValueType  # 1
    UNDERLYINGSOURCE_ADJUSTEDSPOT: _UnderlyingSourceType.ValueType  # 2
    UNDERLYINGSOURCE_IMPLIEDSPOT: _UnderlyingSourceType.ValueType  # 3
    UNDERLYINGSOURCE_DELIVERABLESPOT: _UnderlyingSourceType.ValueType  # 4
class UnderlyingSourceType(_UnderlyingSourceType, metaclass=_UnderlyingSourceTypeEnumTypeWrapper):
    """BEGIN ENUMS

    """
    pass

UNDERLYINGSOURCE_UNKNOWN: UnderlyingSourceType.ValueType  # 0
UNDERLYINGSOURCE_TRUESPOT: UnderlyingSourceType.ValueType  # 1
UNDERLYINGSOURCE_ADJUSTEDSPOT: UnderlyingSourceType.ValueType  # 2
UNDERLYINGSOURCE_IMPLIEDSPOT: UnderlyingSourceType.ValueType  # 3
UNDERLYINGSOURCE_DELIVERABLESPOT: UnderlyingSourceType.ValueType  # 4
global___UnderlyingSourceType = UnderlyingSourceType


class _PriceSourceType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _PriceSourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PriceSourceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRICESOURCE_UNKNOWN: _PriceSourceType.ValueType  # 0
    PRICESOURCE_SPREADAVERAGE: _PriceSourceType.ValueType  # 1
    PRICESOURCE_SETTLEMENT: _PriceSourceType.ValueType  # 2
    PRICESOURCE_MANUAL: _PriceSourceType.ValueType  # 3
    PRICESOURCE_SCRIPT: _PriceSourceType.ValueType  # 4
class PriceSourceType(_PriceSourceType, metaclass=_PriceSourceTypeEnumTypeWrapper):
    pass

PRICESOURCE_UNKNOWN: PriceSourceType.ValueType  # 0
PRICESOURCE_SPREADAVERAGE: PriceSourceType.ValueType  # 1
PRICESOURCE_SETTLEMENT: PriceSourceType.ValueType  # 2
PRICESOURCE_MANUAL: PriceSourceType.ValueType  # 3
PRICESOURCE_SCRIPT: PriceSourceType.ValueType  # 4
global___PriceSourceType = PriceSourceType


class _UnderlyingBboType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _UnderlyingBboTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UnderlyingBboType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNDERLYINGBBO_UNKNOWN: _UnderlyingBboType.ValueType  # 0
    UNDERLYINGBBO_MAIN: _UnderlyingBboType.ValueType  # 1
    UNDERLYINGBBO_FOREIGN: _UnderlyingBboType.ValueType  # 2
    UNDERLYINGBBO_BEST: _UnderlyingBboType.ValueType  # 3
    UNDERLYINGBBO_INDICATIVE: _UnderlyingBboType.ValueType  # 4
    UNDERLYINGBBO_MODIFIER: _UnderlyingBboType.ValueType  # 5
    UNDERLYINGBBO_AWAY: _UnderlyingBboType.ValueType  # 6
class UnderlyingBboType(_UnderlyingBboType, metaclass=_UnderlyingBboTypeEnumTypeWrapper):
    pass

UNDERLYINGBBO_UNKNOWN: UnderlyingBboType.ValueType  # 0
UNDERLYINGBBO_MAIN: UnderlyingBboType.ValueType  # 1
UNDERLYINGBBO_FOREIGN: UnderlyingBboType.ValueType  # 2
UNDERLYINGBBO_BEST: UnderlyingBboType.ValueType  # 3
UNDERLYINGBBO_INDICATIVE: UnderlyingBboType.ValueType  # 4
UNDERLYINGBBO_MODIFIER: UnderlyingBboType.ValueType  # 5
UNDERLYINGBBO_AWAY: UnderlyingBboType.ValueType  # 6
global___UnderlyingBboType = UnderlyingBboType


class _ImpliedVolatilityBboType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ImpliedVolatilityBboTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ImpliedVolatilityBboType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IMPLIEDVOLATILITYBBO_UNKNOWN: _ImpliedVolatilityBboType.ValueType  # 0
    IMPLIEDVOLATILITYBBO_MAIN: _ImpliedVolatilityBboType.ValueType  # 1
    IMPLIEDVOLATILITYBBO_FOREIGN: _ImpliedVolatilityBboType.ValueType  # 2
class ImpliedVolatilityBboType(_ImpliedVolatilityBboType, metaclass=_ImpliedVolatilityBboTypeEnumTypeWrapper):
    pass

IMPLIEDVOLATILITYBBO_UNKNOWN: ImpliedVolatilityBboType.ValueType  # 0
IMPLIEDVOLATILITYBBO_MAIN: ImpliedVolatilityBboType.ValueType  # 1
IMPLIEDVOLATILITYBBO_FOREIGN: ImpliedVolatilityBboType.ValueType  # 2
global___ImpliedVolatilityBboType = ImpliedVolatilityBboType


class _ImpliedVolatilityCalculationMode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ImpliedVolatilityCalculationModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ImpliedVolatilityCalculationMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IMPLIEDVOLATILITYCALCULATIONMODE_UNKNOWN: _ImpliedVolatilityCalculationMode.ValueType  # 0
    IMPLIEDVOLATILITYCALCULATIONMODE_BIDASK: _ImpliedVolatilityCalculationMode.ValueType  # 1
    IMPLIEDVOLATILITYCALCULATIONMODE_AVERAGE: _ImpliedVolatilityCalculationMode.ValueType  # 2
    IMPLIEDVOLATILITYCALCULATIONMODE_AVERAGEORBIDASK: _ImpliedVolatilityCalculationMode.ValueType  # 3
    IMPLIEDVOLATILITYCALCULATIONMODE_AVERAGEANDBIDASK: _ImpliedVolatilityCalculationMode.ValueType  # 4
    IMPLIEDVOLATILITYCALCULATIONMODE_BIDASKANDLAST: _ImpliedVolatilityCalculationMode.ValueType  # 5
class ImpliedVolatilityCalculationMode(_ImpliedVolatilityCalculationMode, metaclass=_ImpliedVolatilityCalculationModeEnumTypeWrapper):
    pass

IMPLIEDVOLATILITYCALCULATIONMODE_UNKNOWN: ImpliedVolatilityCalculationMode.ValueType  # 0
IMPLIEDVOLATILITYCALCULATIONMODE_BIDASK: ImpliedVolatilityCalculationMode.ValueType  # 1
IMPLIEDVOLATILITYCALCULATIONMODE_AVERAGE: ImpliedVolatilityCalculationMode.ValueType  # 2
IMPLIEDVOLATILITYCALCULATIONMODE_AVERAGEORBIDASK: ImpliedVolatilityCalculationMode.ValueType  # 3
IMPLIEDVOLATILITYCALCULATIONMODE_AVERAGEANDBIDASK: ImpliedVolatilityCalculationMode.ValueType  # 4
IMPLIEDVOLATILITYCALCULATIONMODE_BIDASKANDLAST: ImpliedVolatilityCalculationMode.ValueType  # 5
global___ImpliedVolatilityCalculationMode = ImpliedVolatilityCalculationMode


class _CopyIVMode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _CopyIVModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CopyIVMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    COPYIMPLIEDVOLATILITYMODE_UNKNOWN: _CopyIVMode.ValueType  # 0
    COPYIMPLIEDVOLATILITYMODE_AVERAGE: _CopyIVMode.ValueType  # 1
    COPYIMPLIEDVOLATILITYMODE_LAST: _CopyIVMode.ValueType  # 2
    COPYIMPLIEDVOLATILITYMODE_AWAYMARKET: _CopyIVMode.ValueType  # 3
    COPYIMPLIEDVOLATILITYMODE_AVERAGEORBIDASK: _CopyIVMode.ValueType  # 4
    COPYIMPLIEDVOLATILITYMODE_DELTAWEIGHTED: _CopyIVMode.ValueType  # 5
    COPYIMPLIEDVOLATILITYMODE_AVERAGEIFBIDANDASK: _CopyIVMode.ValueType  # 6
    COPYIMPLIEDVOLATILITYMODE_LOWESTPRICE: _CopyIVMode.ValueType  # 7
class CopyIVMode(_CopyIVMode, metaclass=_CopyIVModeEnumTypeWrapper):
    pass

COPYIMPLIEDVOLATILITYMODE_UNKNOWN: CopyIVMode.ValueType  # 0
COPYIMPLIEDVOLATILITYMODE_AVERAGE: CopyIVMode.ValueType  # 1
COPYIMPLIEDVOLATILITYMODE_LAST: CopyIVMode.ValueType  # 2
COPYIMPLIEDVOLATILITYMODE_AWAYMARKET: CopyIVMode.ValueType  # 3
COPYIMPLIEDVOLATILITYMODE_AVERAGEORBIDASK: CopyIVMode.ValueType  # 4
COPYIMPLIEDVOLATILITYMODE_DELTAWEIGHTED: CopyIVMode.ValueType  # 5
COPYIMPLIEDVOLATILITYMODE_AVERAGEIFBIDANDASK: CopyIVMode.ValueType  # 6
COPYIMPLIEDVOLATILITYMODE_LOWESTPRICE: CopyIVMode.ValueType  # 7
global___CopyIVMode = CopyIVMode


class _VolatilityRangeSpecificationType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _VolatilityRangeSpecificationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VolatilityRangeSpecificationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VOLATILITYRANGESPECIFICATIONTYPE_MIN: _VolatilityRangeSpecificationType.ValueType  # 0
    VOLATILITYRANGESPECIFICATIONTYPE_STANDARD: _VolatilityRangeSpecificationType.ValueType  # 1
    VOLATILITYRANGESPECIFICATIONTYPE_CONFIGURABLTETYPE1: _VolatilityRangeSpecificationType.ValueType  # 2
class VolatilityRangeSpecificationType(_VolatilityRangeSpecificationType, metaclass=_VolatilityRangeSpecificationTypeEnumTypeWrapper):
    pass

VOLATILITYRANGESPECIFICATIONTYPE_MIN: VolatilityRangeSpecificationType.ValueType  # 0
VOLATILITYRANGESPECIFICATIONTYPE_STANDARD: VolatilityRangeSpecificationType.ValueType  # 1
VOLATILITYRANGESPECIFICATIONTYPE_CONFIGURABLTETYPE1: VolatilityRangeSpecificationType.ValueType  # 2
global___VolatilityRangeSpecificationType = VolatilityRangeSpecificationType


class _SmoothThetaType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _SmoothThetaTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SmoothThetaType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SMOOTHTHETATYPE_UNKNOWN: _SmoothThetaType.ValueType  # 0
    SMOOTHTHETATYPE_OFF: _SmoothThetaType.ValueType  # 1
    SMOOTHTHETATYPE_ON: _SmoothThetaType.ValueType  # 2
    SMOOTHTHETATYPE_CAPPED: _SmoothThetaType.ValueType  # 3
    SMOOTHTHETATYPE_CAPPEDNORMALIZED: _SmoothThetaType.ValueType  # 4
    SMOOTHTHETATYPE_DAILY: _SmoothThetaType.ValueType  # 5
class SmoothThetaType(_SmoothThetaType, metaclass=_SmoothThetaTypeEnumTypeWrapper):
    pass

SMOOTHTHETATYPE_UNKNOWN: SmoothThetaType.ValueType  # 0
SMOOTHTHETATYPE_OFF: SmoothThetaType.ValueType  # 1
SMOOTHTHETATYPE_ON: SmoothThetaType.ValueType  # 2
SMOOTHTHETATYPE_CAPPED: SmoothThetaType.ValueType  # 3
SMOOTHTHETATYPE_CAPPEDNORMALIZED: SmoothThetaType.ValueType  # 4
SMOOTHTHETATYPE_DAILY: SmoothThetaType.ValueType  # 5
global___SmoothThetaType = SmoothThetaType


class _RateConfiguration:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RateConfigurationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RateConfiguration.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RATECONFIGURATION_UNKNOWN: _RateConfiguration.ValueType  # 0
    RATECONFIGURATION_PREMIUMANDSTOCK: _RateConfiguration.ValueType  # 1
    RATECONFIGURATION_PREMIUM: _RateConfiguration.ValueType  # 2
    RATECONFIGURATION_STOCK: _RateConfiguration.ValueType  # 3
    RATECONFIGURATION_PREMIUMANDDIVIDEND: _RateConfiguration.ValueType  # 4
class RateConfiguration(_RateConfiguration, metaclass=_RateConfigurationEnumTypeWrapper):
    pass

RATECONFIGURATION_UNKNOWN: RateConfiguration.ValueType  # 0
RATECONFIGURATION_PREMIUMANDSTOCK: RateConfiguration.ValueType  # 1
RATECONFIGURATION_PREMIUM: RateConfiguration.ValueType  # 2
RATECONFIGURATION_STOCK: RateConfiguration.ValueType  # 3
RATECONFIGURATION_PREMIUMANDDIVIDEND: RateConfiguration.ValueType  # 4
global___RateConfiguration = RateConfiguration


class _TimeUnit:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _TimeUnitEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TimeUnit.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TIMEUNIT_UNKNOWN: _TimeUnit.ValueType  # 0
    TIMEUNIT_DAY: _TimeUnit.ValueType  # 1
    TIMEUNIT_WEEK: _TimeUnit.ValueType  # 2
    TIMEUNIT_MONTH: _TimeUnit.ValueType  # 3
    TIMEUNIT_YEAR: _TimeUnit.ValueType  # 4
class TimeUnit(_TimeUnit, metaclass=_TimeUnitEnumTypeWrapper):
    pass

TIMEUNIT_UNKNOWN: TimeUnit.ValueType  # 0
TIMEUNIT_DAY: TimeUnit.ValueType  # 1
TIMEUNIT_WEEK: TimeUnit.ValueType  # 2
TIMEUNIT_MONTH: TimeUnit.ValueType  # 3
TIMEUNIT_YEAR: TimeUnit.ValueType  # 4
global___TimeUnit = TimeUnit


class _RateAdjustmentType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RateAdjustmentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RateAdjustmentType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RATEADJUSTMENTTYPE_UNKNOWN: _RateAdjustmentType.ValueType  # 0
    RATEADJUSTMENTTYPE_FIXED: _RateAdjustmentType.ValueType  # 1
    RATEADJUSTMENTTYPE_CONSTANTOFFSET: _RateAdjustmentType.ValueType  # 2
class RateAdjustmentType(_RateAdjustmentType, metaclass=_RateAdjustmentTypeEnumTypeWrapper):
    pass

RATEADJUSTMENTTYPE_UNKNOWN: RateAdjustmentType.ValueType  # 0
RATEADJUSTMENTTYPE_FIXED: RateAdjustmentType.ValueType  # 1
RATEADJUSTMENTTYPE_CONSTANTOFFSET: RateAdjustmentType.ValueType  # 2
global___RateAdjustmentType = RateAdjustmentType


class _VolatilityType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _VolatilityTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VolatilityType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VOLATILITYTYPE_UNKNOWN: _VolatilityType.ValueType  # 0
    VOLATILITYTYPE_MANUAL: _VolatilityType.ValueType  # 1
    VOLATILITYTYPE_SCRIPT: _VolatilityType.ValueType  # 2
    VOLATILITYTYPE_SABR: _VolatilityType.ValueType  # 3
class VolatilityType(_VolatilityType, metaclass=_VolatilityTypeEnumTypeWrapper):
    pass

VOLATILITYTYPE_UNKNOWN: VolatilityType.ValueType  # 0
VOLATILITYTYPE_MANUAL: VolatilityType.ValueType  # 1
VOLATILITYTYPE_SCRIPT: VolatilityType.ValueType  # 2
VOLATILITYTYPE_SABR: VolatilityType.ValueType  # 3
global___VolatilityType = VolatilityType


class ValuationContext(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SEQUENCENUMBER_FIELD_NUMBER: builtins.int
    UNDERLYINGSOURCE_FIELD_NUMBER: builtins.int
    FORMULAS_FIELD_NUMBER: builtins.int
    CORRECTIONS_FIELD_NUMBER: builtins.int
    DAYCORRECTIONS_FIELD_NUMBER: builtins.int
    GREEKS_FIELD_NUMBER: builtins.int
    TIMECONTROL_FIELD_NUMBER: builtins.int
    IMPLIEDVOLATILITYSETTINGS_FIELD_NUMBER: builtins.int
    IMPLIEDVOLATILITYSMOOTHING_FIELD_NUMBER: builtins.int
    BASISADJUSTMENT_FIELD_NUMBER: builtins.int
    OPTIONALCALCULATIONS_FIELD_NUMBER: builtins.int
    FILTERS_FIELD_NUMBER: builtins.int
    PRECALCSETTINGS_FIELD_NUMBER: builtins.int
    DIVIDENDS_FIELD_NUMBER: builtins.int
    TIMEDECAY_FIELD_NUMBER: builtins.int
    RATESETTINGS_FIELD_NUMBER: builtins.int
    BASISANDOFFSETS_FIELD_NUMBER: builtins.int
    PREMIUMRATES_FIELD_NUMBER: builtins.int
    STOCKRATES_FIELD_NUMBER: builtins.int
    DIVIDENDRATES_FIELD_NUMBER: builtins.int
    VOLATILITYSETTINGS_FIELD_NUMBER: builtins.int
    SABRVOLATILITY_FIELD_NUMBER: builtins.int
    MANUALVOLATILITY_FIELD_NUMBER: builtins.int
    sequenceNumber: builtins.int
    @property
    def underlyingSource(self) -> global___UnderlyingSource: ...
    @property
    def formulas(self) -> global___Formulas: ...
    @property
    def corrections(self) -> global___Corrections: ...
    @property
    def dayCorrections(self) -> global___DayCorrections: ...
    @property
    def greeks(self) -> global___Greeks: ...
    @property
    def timeControl(self) -> global___TimeControl: ...
    @property
    def impliedVolatilitySettings(self) -> global___ImpliedVolatilitySettings: ...
    @property
    def impliedVolatilitySmoothing(self) -> global___ImpliedVolatilitySmoothing: ...
    @property
    def basisAdjustment(self) -> global___BasisAdjustment: ...
    @property
    def optionalCalculations(self) -> global___OptionalCalculations: ...
    @property
    def filters(self) -> global___Filters: ...
    @property
    def precalcSettings(self) -> global___PrecalcSettings: ...
    @property
    def dividends(self) -> global___Dividends: ...
    @property
    def timeDecay(self) -> global___TimeDecay: ...
    @property
    def rateSettings(self) -> global___RateSettings: ...
    @property
    def basisAndOffsets(self) -> global___BasisAndOffsets: ...
    @property
    def premiumRates(self) -> global___PremiumRates: ...
    @property
    def stockRates(self) -> global___StockRates: ...
    @property
    def dividendRates(self) -> global___DividendRates: ...
    @property
    def volatilitySettings(self) -> global___VolatilitySettings: ...
    @property
    def sabrVolatility(self) -> global___SABRVolatility: ...
    @property
    def manualVolatility(self) -> global___ManualVolatility: ...
    def __init__(self,
        *,
        sequenceNumber: typing.Optional[builtins.int] = ...,
        underlyingSource: typing.Optional[global___UnderlyingSource] = ...,
        formulas: typing.Optional[global___Formulas] = ...,
        corrections: typing.Optional[global___Corrections] = ...,
        dayCorrections: typing.Optional[global___DayCorrections] = ...,
        greeks: typing.Optional[global___Greeks] = ...,
        timeControl: typing.Optional[global___TimeControl] = ...,
        impliedVolatilitySettings: typing.Optional[global___ImpliedVolatilitySettings] = ...,
        impliedVolatilitySmoothing: typing.Optional[global___ImpliedVolatilitySmoothing] = ...,
        basisAdjustment: typing.Optional[global___BasisAdjustment] = ...,
        optionalCalculations: typing.Optional[global___OptionalCalculations] = ...,
        filters: typing.Optional[global___Filters] = ...,
        precalcSettings: typing.Optional[global___PrecalcSettings] = ...,
        dividends: typing.Optional[global___Dividends] = ...,
        timeDecay: typing.Optional[global___TimeDecay] = ...,
        rateSettings: typing.Optional[global___RateSettings] = ...,
        basisAndOffsets: typing.Optional[global___BasisAndOffsets] = ...,
        premiumRates: typing.Optional[global___PremiumRates] = ...,
        stockRates: typing.Optional[global___StockRates] = ...,
        dividendRates: typing.Optional[global___DividendRates] = ...,
        volatilitySettings: typing.Optional[global___VolatilitySettings] = ...,
        sabrVolatility: typing.Optional[global___SABRVolatility] = ...,
        manualVolatility: typing.Optional[global___ManualVolatility] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["basisAdjustment",b"basisAdjustment","basisAndOffsets",b"basisAndOffsets","corrections",b"corrections","dayCorrections",b"dayCorrections","dividendRates",b"dividendRates","dividends",b"dividends","filters",b"filters","formulas",b"formulas","greeks",b"greeks","impliedVolatilitySettings",b"impliedVolatilitySettings","impliedVolatilitySmoothing",b"impliedVolatilitySmoothing","manualVolatility",b"manualVolatility","optionalCalculations",b"optionalCalculations","precalcSettings",b"precalcSettings","premiumRates",b"premiumRates","rateSettings",b"rateSettings","sabrVolatility",b"sabrVolatility","sequenceNumber",b"sequenceNumber","stockRates",b"stockRates","timeControl",b"timeControl","timeDecay",b"timeDecay","underlyingSource",b"underlyingSource","volatilitySettings",b"volatilitySettings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["basisAdjustment",b"basisAdjustment","basisAndOffsets",b"basisAndOffsets","corrections",b"corrections","dayCorrections",b"dayCorrections","dividendRates",b"dividendRates","dividends",b"dividends","filters",b"filters","formulas",b"formulas","greeks",b"greeks","impliedVolatilitySettings",b"impliedVolatilitySettings","impliedVolatilitySmoothing",b"impliedVolatilitySmoothing","manualVolatility",b"manualVolatility","optionalCalculations",b"optionalCalculations","precalcSettings",b"precalcSettings","premiumRates",b"premiumRates","rateSettings",b"rateSettings","sabrVolatility",b"sabrVolatility","sequenceNumber",b"sequenceNumber","stockRates",b"stockRates","timeControl",b"timeControl","timeDecay",b"timeDecay","underlyingSource",b"underlyingSource","volatilitySettings",b"volatilitySettings"]) -> None: ...
global___ValuationContext = ValuationContext

class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTTYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    UNDERLYING_FIELD_NUMBER: builtins.int
    VALUATIONCONTEXT_FIELD_NUMBER: builtins.int
    requestType: global___RequestType.ValueType
    clientId: builtins.int
    underlying: typing.Text
    @property
    def valuationContext(self) -> global___ValuationContext: ...
    def __init__(self,
        *,
        requestType: typing.Optional[global___RequestType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        underlying: typing.Optional[typing.Text] = ...,
        valuationContext: typing.Optional[global___ValuationContext] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","requestType",b"requestType","underlying",b"underlying","valuationContext",b"valuationContext"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","requestType",b"requestType","underlying",b"underlying","valuationContext",b"valuationContext"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSETYPE_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    UNDERLYING_FIELD_NUMBER: builtins.int
    OPERATIONSTATUS_FIELD_NUMBER: builtins.int
    VALUATIONCONTEXT_FIELD_NUMBER: builtins.int
    UNDERLYINGS_FIELD_NUMBER: builtins.int
    responseType: global___ResponseType.ValueType
    clientId: builtins.int
    """only request responses"""

    underlying: typing.Text
    @property
    def operationStatus(self) -> ActTypes_pb2.OperationStatus: ...
    @property
    def valuationContext(self) -> global___ValuationContext: ...
    @property
    def underlyings(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        responseType: typing.Optional[global___ResponseType.ValueType] = ...,
        clientId: typing.Optional[builtins.int] = ...,
        underlying: typing.Optional[typing.Text] = ...,
        operationStatus: typing.Optional[ActTypes_pb2.OperationStatus] = ...,
        valuationContext: typing.Optional[global___ValuationContext] = ...,
        underlyings: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType","underlying",b"underlying","valuationContext",b"valuationContext"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clientId",b"clientId","operationStatus",b"operationStatus","responseType",b"responseType","underlying",b"underlying","underlyings",b"underlyings","valuationContext",b"valuationContext"]) -> None: ...
global___Response = Response

class UnderlyingSource(google.protobuf.message.Message):
    """END ENUMS

    BEGIN UNDERLYING SOURCE

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UNDERLYINGSOURCETYPE_FIELD_NUMBER: builtins.int
    FUTUREINDEX_FIELD_NUMBER: builtins.int
    FORWARDSAREUNDERLYING_FIELD_NUMBER: builtins.int
    PRICESOURCETYPE_FIELD_NUMBER: builtins.int
    BBOTYPE_FIELD_NUMBER: builtins.int
    UNDERLYINGSCRIPTNAME_FIELD_NUMBER: builtins.int
    SEPARATESOURCEATEXPIRY_FIELD_NUMBER: builtins.int
    underlyingSourceType: global___UnderlyingSourceType.ValueType
    futureIndex: builtins.int
    forwardsAreUnderlying: builtins.bool
    priceSourceType: global___PriceSourceType.ValueType
    bboType: global___UnderlyingBboType.ValueType
    underlyingScriptName: typing.Text
    separateSourceAtExpiry: builtins.bool
    def __init__(self,
        *,
        underlyingSourceType: typing.Optional[global___UnderlyingSourceType.ValueType] = ...,
        futureIndex: typing.Optional[builtins.int] = ...,
        forwardsAreUnderlying: typing.Optional[builtins.bool] = ...,
        priceSourceType: typing.Optional[global___PriceSourceType.ValueType] = ...,
        bboType: typing.Optional[global___UnderlyingBboType.ValueType] = ...,
        underlyingScriptName: typing.Optional[typing.Text] = ...,
        separateSourceAtExpiry: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bboType",b"bboType","forwardsAreUnderlying",b"forwardsAreUnderlying","futureIndex",b"futureIndex","priceSourceType",b"priceSourceType","separateSourceAtExpiry",b"separateSourceAtExpiry","underlyingScriptName",b"underlyingScriptName","underlyingSourceType",b"underlyingSourceType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bboType",b"bboType","forwardsAreUnderlying",b"forwardsAreUnderlying","futureIndex",b"futureIndex","priceSourceType",b"priceSourceType","separateSourceAtExpiry",b"separateSourceAtExpiry","underlyingScriptName",b"underlyingScriptName","underlyingSourceType",b"underlyingSourceType"]) -> None: ...
global___UnderlyingSource = UnderlyingSource

class Formulas(google.protobuf.message.Message):
    """END UNDERLYING SOURCE

    BEGIN FORMULAS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FUTUREFORMULA_FIELD_NUMBER: builtins.int
    CALLFORMULA_FIELD_NUMBER: builtins.int
    PUTFORMULA_FIELD_NUMBER: builtins.int
    LONGTERMCALLFORMULA_FIELD_NUMBER: builtins.int
    LONGTERMPUTFORMULA_FIELD_NUMBER: builtins.int
    FORCEBLACKSCHOLESFORAMERICANOPTIONS_FIELD_NUMBER: builtins.int
    USELONGTERMFORMULAS_FIELD_NUMBER: builtins.int
    LONGTERMEXPIRATIONINDEX_FIELD_NUMBER: builtins.int
    futureFormula: typing.Text
    callFormula: typing.Text
    putFormula: typing.Text
    longTermCallFormula: typing.Text
    longTermPutFormula: typing.Text
    forceBlackScholesForAmericanOptions: builtins.bool
    useLongTermFormulas: builtins.bool
    longTermExpirationIndex: builtins.int
    def __init__(self,
        *,
        futureFormula: typing.Optional[typing.Text] = ...,
        callFormula: typing.Optional[typing.Text] = ...,
        putFormula: typing.Optional[typing.Text] = ...,
        longTermCallFormula: typing.Optional[typing.Text] = ...,
        longTermPutFormula: typing.Optional[typing.Text] = ...,
        forceBlackScholesForAmericanOptions: typing.Optional[builtins.bool] = ...,
        useLongTermFormulas: typing.Optional[builtins.bool] = ...,
        longTermExpirationIndex: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["callFormula",b"callFormula","forceBlackScholesForAmericanOptions",b"forceBlackScholesForAmericanOptions","futureFormula",b"futureFormula","longTermCallFormula",b"longTermCallFormula","longTermExpirationIndex",b"longTermExpirationIndex","longTermPutFormula",b"longTermPutFormula","putFormula",b"putFormula","useLongTermFormulas",b"useLongTermFormulas"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["callFormula",b"callFormula","forceBlackScholesForAmericanOptions",b"forceBlackScholesForAmericanOptions","futureFormula",b"futureFormula","longTermCallFormula",b"longTermCallFormula","longTermExpirationIndex",b"longTermExpirationIndex","longTermPutFormula",b"longTermPutFormula","putFormula",b"putFormula","useLongTermFormulas",b"useLongTermFormulas"]) -> None: ...
global___Formulas = Formulas

class Corrections(google.protobuf.message.Message):
    """END FORMULAS

    BEGIN CORRECTIONS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UNDERLYINGZEROOFFSET_FIELD_NUMBER: builtins.int
    ZEROPREMIUMRATE_FIELD_NUMBER: builtins.int
    FULLRATECURVE_FIELD_NUMBER: builtins.int
    underlyingZeroOffset: builtins.float
    zeroPremiumRate: builtins.bool
    fullRateCurve: builtins.bool
    def __init__(self,
        *,
        underlyingZeroOffset: typing.Optional[builtins.float] = ...,
        zeroPremiumRate: typing.Optional[builtins.bool] = ...,
        fullRateCurve: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fullRateCurve",b"fullRateCurve","underlyingZeroOffset",b"underlyingZeroOffset","zeroPremiumRate",b"zeroPremiumRate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fullRateCurve",b"fullRateCurve","underlyingZeroOffset",b"underlyingZeroOffset","zeroPremiumRate",b"zeroPremiumRate"]) -> None: ...
global___Corrections = Corrections

class DayCorrections(google.protobuf.message.Message):
    """END CORRECTIONS

    BEGIN DAY CORRECTIONS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DAYCORRECTION_FIELD_NUMBER: builtins.int
    GLOBALDAYCORRECTION_FIELD_NUMBER: builtins.int
    dayCorrection: builtins.float
    globalDayCorrection: builtins.float
    def __init__(self,
        *,
        dayCorrection: typing.Optional[builtins.float] = ...,
        globalDayCorrection: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dayCorrection",b"dayCorrection","globalDayCorrection",b"globalDayCorrection"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dayCorrection",b"dayCorrection","globalDayCorrection",b"globalDayCorrection"]) -> None: ...
global___DayCorrections = DayCorrections

class Greeks(google.protobuf.message.Message):
    """END DAY CORRECTIONS

    BEGIN GREEKS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GREEKSONFUTURE_FIELD_NUMBER: builtins.int
    MULTIPLEFUTURES_FIELD_NUMBER: builtins.int
    USEVOLATILITYSLOPE_FIELD_NUMBER: builtins.int
    UNDERLYINGSCALING_FIELD_NUMBER: builtins.int
    greeksOnFuture: builtins.bool
    multipleFutures: builtins.bool
    useVolatilitySlope: builtins.bool
    underlyingScaling: builtins.float
    def __init__(self,
        *,
        greeksOnFuture: typing.Optional[builtins.bool] = ...,
        multipleFutures: typing.Optional[builtins.bool] = ...,
        useVolatilitySlope: typing.Optional[builtins.bool] = ...,
        underlyingScaling: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["greeksOnFuture",b"greeksOnFuture","multipleFutures",b"multipleFutures","underlyingScaling",b"underlyingScaling","useVolatilitySlope",b"useVolatilitySlope"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["greeksOnFuture",b"greeksOnFuture","multipleFutures",b"multipleFutures","underlyingScaling",b"underlyingScaling","useVolatilitySlope",b"useVolatilitySlope"]) -> None: ...
global___Greeks = Greeks

class TimeControl(google.protobuf.message.Message):
    """END GREEKS

    BEGIN TIME CONTROL

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DECAYPERIOD_FIELD_NUMBER: builtins.int
    decayPeriod: builtins.int
    def __init__(self,
        *,
        decayPeriod: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["decayPeriod",b"decayPeriod"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["decayPeriod",b"decayPeriod"]) -> None: ...
global___TimeControl = TimeControl

class ImpliedVolatilitySettings(google.protobuf.message.Message):
    """END TIME CONTROL

    BEGIN IMPLIED VOLATILTY SETTINGS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IMPLIEDVOLATILITYCALCULATIONMODE_FIELD_NUMBER: builtins.int
    IMPLIEDVOLATILITYBBOTYPE_FIELD_NUMBER: builtins.int
    impliedVolatilityCalculationMode: global___ImpliedVolatilityCalculationMode.ValueType
    impliedVolatilityBboType: global___ImpliedVolatilityBboType.ValueType
    def __init__(self,
        *,
        impliedVolatilityCalculationMode: typing.Optional[global___ImpliedVolatilityCalculationMode.ValueType] = ...,
        impliedVolatilityBboType: typing.Optional[global___ImpliedVolatilityBboType.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["impliedVolatilityBboType",b"impliedVolatilityBboType","impliedVolatilityCalculationMode",b"impliedVolatilityCalculationMode"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["impliedVolatilityBboType",b"impliedVolatilityBboType","impliedVolatilityCalculationMode",b"impliedVolatilityCalculationMode"]) -> None: ...
global___ImpliedVolatilitySettings = ImpliedVolatilitySettings

class ImpliedVolatilitySmoothing(google.protobuf.message.Message):
    """END IMPLIED VOLATILTY SETTINGS

    BEGIN IMPLIED VOLATILITY SMOOTHING

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SMOOTHIVENABLED_FIELD_NUMBER: builtins.int
    SMOOTHIVCOEFFICIENT_FIELD_NUMBER: builtins.int
    COPYIVMODE_FIELD_NUMBER: builtins.int
    DELTACUTOFF_FIELD_NUMBER: builtins.int
    WINDOWSIZE_FIELD_NUMBER: builtins.int
    smoothIVEnabled: builtins.bool
    smoothIVCoefficient: builtins.float
    copyIVMode: global___CopyIVMode.ValueType
    deltaCutoff: builtins.float
    windowSize: builtins.int
    def __init__(self,
        *,
        smoothIVEnabled: typing.Optional[builtins.bool] = ...,
        smoothIVCoefficient: typing.Optional[builtins.float] = ...,
        copyIVMode: typing.Optional[global___CopyIVMode.ValueType] = ...,
        deltaCutoff: typing.Optional[builtins.float] = ...,
        windowSize: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["copyIVMode",b"copyIVMode","deltaCutoff",b"deltaCutoff","smoothIVCoefficient",b"smoothIVCoefficient","smoothIVEnabled",b"smoothIVEnabled","windowSize",b"windowSize"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["copyIVMode",b"copyIVMode","deltaCutoff",b"deltaCutoff","smoothIVCoefficient",b"smoothIVCoefficient","smoothIVEnabled",b"smoothIVEnabled","windowSize",b"windowSize"]) -> None: ...
global___ImpliedVolatilitySmoothing = ImpliedVolatilitySmoothing

class BasisAdjustment(google.protobuf.message.Message):
    """END IMPLIED VOLATILITY SMOOTHING

    BEGIN BASIS ADJUSTMENT

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USEMANUALADJUSTMENT_FIELD_NUMBER: builtins.int
    MANUALBASISADJUSTMENT_FIELD_NUMBER: builtins.int
    useManualAdjustment: builtins.bool
    manualBasisAdjustment: builtins.float
    def __init__(self,
        *,
        useManualAdjustment: typing.Optional[builtins.bool] = ...,
        manualBasisAdjustment: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["manualBasisAdjustment",b"manualBasisAdjustment","useManualAdjustment",b"useManualAdjustment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["manualBasisAdjustment",b"manualBasisAdjustment","useManualAdjustment",b"useManualAdjustment"]) -> None: ...
global___BasisAdjustment = BasisAdjustment

class OptionalCalculations(google.protobuf.message.Message):
    """END BASIS ADJUSTMENT

    BEGIN OPTIONAL CALCULATIONS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMPUTEFLATTHEORETICAL_FIELD_NUMBER: builtins.int
    COMPUTEIMPLIEDVOLATILITY_FIELD_NUMBER: builtins.int
    COMPUTEVEGA_FIELD_NUMBER: builtins.int
    COMPUTERHO_FIELD_NUMBER: builtins.int
    computeFlatTheoretical: builtins.bool
    computeImpliedVolatility: builtins.bool
    computeVega: builtins.bool
    computeRho: builtins.bool
    def __init__(self,
        *,
        computeFlatTheoretical: typing.Optional[builtins.bool] = ...,
        computeImpliedVolatility: typing.Optional[builtins.bool] = ...,
        computeVega: typing.Optional[builtins.bool] = ...,
        computeRho: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["computeFlatTheoretical",b"computeFlatTheoretical","computeImpliedVolatility",b"computeImpliedVolatility","computeRho",b"computeRho","computeVega",b"computeVega"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["computeFlatTheoretical",b"computeFlatTheoretical","computeImpliedVolatility",b"computeImpliedVolatility","computeRho",b"computeRho","computeVega",b"computeVega"]) -> None: ...
global___OptionalCalculations = OptionalCalculations

class Filters(google.protobuf.message.Message):
    """END OPTIONAL CALCULATIONS

    BEGIN FILTERS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UNDERLYINGRECALCULATIONFILTER_FIELD_NUMBER: builtins.int
    DERIVATIVERECALCULATIONFILTER_FIELD_NUMBER: builtins.int
    LOCKSTEPFILTER_FIELD_NUMBER: builtins.int
    underlyingRecalculationFilter: typing.Text
    derivativeRecalculationFilter: builtins.float
    lockStepFilter: builtins.float
    def __init__(self,
        *,
        underlyingRecalculationFilter: typing.Optional[typing.Text] = ...,
        derivativeRecalculationFilter: typing.Optional[builtins.float] = ...,
        lockStepFilter: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["derivativeRecalculationFilter",b"derivativeRecalculationFilter","lockStepFilter",b"lockStepFilter","underlyingRecalculationFilter",b"underlyingRecalculationFilter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["derivativeRecalculationFilter",b"derivativeRecalculationFilter","lockStepFilter",b"lockStepFilter","underlyingRecalculationFilter",b"underlyingRecalculationFilter"]) -> None: ...
global___Filters = Filters

class PrecalcSettings(google.protobuf.message.Message):
    """END FILTERS

    BEGIN PRECALC SETTINGS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRECALCENABLED_FIELD_NUMBER: builtins.int
    NUMBEROFINITIALUNDERLYINGSTEPS_FIELD_NUMBER: builtins.int
    UNDERLYINGRANGEINPERCENTAGE_FIELD_NUMBER: builtins.int
    AUTOOPTIONERRORENABLED_FIELD_NUMBER: builtins.int
    ABSOLUTEOPTIONERROR_FIELD_NUMBER: builtins.int
    ABSOLUTEVOLATILITYERROR_FIELD_NUMBER: builtins.int
    VOLATILITYRANGESPECIFICATIONTYPE_FIELD_NUMBER: builtins.int
    VOLATILITYRANGE_FIELD_NUMBER: builtins.int
    LOWERVOLATILITYBOUNDARY_FIELD_NUMBER: builtins.int
    CORRECTEDGREEKENABLED_FIELD_NUMBER: builtins.int
    PRECALCULATEVOLATILITYENABLED_FIELD_NUMBER: builtins.int
    precalcEnabled: builtins.bool
    numberOfInitialUnderlyingSteps: builtins.int
    underlyingRangeInPercentage: builtins.float
    autoOptionErrorEnabled: builtins.bool
    absoluteOptionError: builtins.float
    absoluteVolatilityError: builtins.float
    volatilityRangeSpecificationType: global___VolatilityRangeSpecificationType.ValueType
    volatilityRange: builtins.float
    lowerVolatilityBoundary: builtins.float
    correctedGreekEnabled: builtins.bool
    precalculateVolatilityEnabled: builtins.bool
    def __init__(self,
        *,
        precalcEnabled: typing.Optional[builtins.bool] = ...,
        numberOfInitialUnderlyingSteps: typing.Optional[builtins.int] = ...,
        underlyingRangeInPercentage: typing.Optional[builtins.float] = ...,
        autoOptionErrorEnabled: typing.Optional[builtins.bool] = ...,
        absoluteOptionError: typing.Optional[builtins.float] = ...,
        absoluteVolatilityError: typing.Optional[builtins.float] = ...,
        volatilityRangeSpecificationType: typing.Optional[global___VolatilityRangeSpecificationType.ValueType] = ...,
        volatilityRange: typing.Optional[builtins.float] = ...,
        lowerVolatilityBoundary: typing.Optional[builtins.float] = ...,
        correctedGreekEnabled: typing.Optional[builtins.bool] = ...,
        precalculateVolatilityEnabled: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["absoluteOptionError",b"absoluteOptionError","absoluteVolatilityError",b"absoluteVolatilityError","autoOptionErrorEnabled",b"autoOptionErrorEnabled","correctedGreekEnabled",b"correctedGreekEnabled","lowerVolatilityBoundary",b"lowerVolatilityBoundary","numberOfInitialUnderlyingSteps",b"numberOfInitialUnderlyingSteps","precalcEnabled",b"precalcEnabled","precalculateVolatilityEnabled",b"precalculateVolatilityEnabled","underlyingRangeInPercentage",b"underlyingRangeInPercentage","volatilityRange",b"volatilityRange","volatilityRangeSpecificationType",b"volatilityRangeSpecificationType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["absoluteOptionError",b"absoluteOptionError","absoluteVolatilityError",b"absoluteVolatilityError","autoOptionErrorEnabled",b"autoOptionErrorEnabled","correctedGreekEnabled",b"correctedGreekEnabled","lowerVolatilityBoundary",b"lowerVolatilityBoundary","numberOfInitialUnderlyingSteps",b"numberOfInitialUnderlyingSteps","precalcEnabled",b"precalcEnabled","precalculateVolatilityEnabled",b"precalculateVolatilityEnabled","underlyingRangeInPercentage",b"underlyingRangeInPercentage","volatilityRange",b"volatilityRange","volatilityRangeSpecificationType",b"volatilityRangeSpecificationType"]) -> None: ...
global___PrecalcSettings = PrecalcSettings

class Dividend(google.protobuf.message.Message):
    """END PRECALC SETTINGS

    BEGIN DIVIDENDS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCHTIME_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    epochTime: builtins.int
    amount: builtins.float
    def __init__(self,
        *,
        epochTime: typing.Optional[builtins.int] = ...,
        amount: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["amount",b"amount","epochTime",b"epochTime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount",b"amount","epochTime",b"epochTime"]) -> None: ...
global___Dividend = Dividend

class Dividends(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ISPROPORTIONAL_FIELD_NUMBER: builtins.int
    DIVIDENDS_FIELD_NUMBER: builtins.int
    isProportional: builtins.bool
    @property
    def dividends(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Dividend]: ...
    def __init__(self,
        *,
        isProportional: typing.Optional[builtins.bool] = ...,
        dividends: typing.Optional[typing.Iterable[global___Dividend]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["isProportional",b"isProportional"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dividends",b"dividends","isProportional",b"isProportional"]) -> None: ...
global___Dividends = Dividends

class HolidayFactor(google.protobuf.message.Message):
    """END DIVIDENDS

    BEGIN TIME DECAY

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCHTIME_FIELD_NUMBER: builtins.int
    FACTOR_FIELD_NUMBER: builtins.int
    epochTime: builtins.int
    factor: builtins.float
    def __init__(self,
        *,
        epochTime: typing.Optional[builtins.int] = ...,
        factor: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["epochTime",b"epochTime","factor",b"factor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["epochTime",b"epochTime","factor",b"factor"]) -> None: ...
global___HolidayFactor = HolidayFactor

class TimeDecay(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SMOOTHTHETATYPE_FIELD_NUMBER: builtins.int
    SMOOTHTHETAFORMULA_FIELD_NUMBER: builtins.int
    BUSINESSDAYFACTOR_FIELD_NUMBER: builtins.int
    HALFHOURLYFACTORS_FIELD_NUMBER: builtins.int
    WEEKLYFACTORS_FIELD_NUMBER: builtins.int
    HOLIDAYFACTORS_FIELD_NUMBER: builtins.int
    smoothThetaType: global___SmoothThetaType.ValueType
    smoothThetaFormula: typing.Text
    businessDayFactor: builtins.float
    @property
    def halfhourlyFactors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """weighting factors"""
        pass
    @property
    def weeklyFactors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def holidayFactors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HolidayFactor]: ...
    def __init__(self,
        *,
        smoothThetaType: typing.Optional[global___SmoothThetaType.ValueType] = ...,
        smoothThetaFormula: typing.Optional[typing.Text] = ...,
        businessDayFactor: typing.Optional[builtins.float] = ...,
        halfhourlyFactors: typing.Optional[typing.Iterable[builtins.float]] = ...,
        weeklyFactors: typing.Optional[typing.Iterable[builtins.float]] = ...,
        holidayFactors: typing.Optional[typing.Iterable[global___HolidayFactor]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["businessDayFactor",b"businessDayFactor","smoothThetaFormula",b"smoothThetaFormula","smoothThetaType",b"smoothThetaType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["businessDayFactor",b"businessDayFactor","halfhourlyFactors",b"halfhourlyFactors","holidayFactors",b"holidayFactors","smoothThetaFormula",b"smoothThetaFormula","smoothThetaType",b"smoothThetaType","weeklyFactors",b"weeklyFactors"]) -> None: ...
global___TimeDecay = TimeDecay

class RateSettings(google.protobuf.message.Message):
    """END TIME DECAY

    BEGIN RATE SETTINGS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RATECONFIGURATION_FIELD_NUMBER: builtins.int
    rateConfiguration: global___RateConfiguration.ValueType
    def __init__(self,
        *,
        rateConfiguration: typing.Optional[global___RateConfiguration.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["rateConfiguration",b"rateConfiguration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["rateConfiguration",b"rateConfiguration"]) -> None: ...
global___RateSettings = RateSettings

class Offset(google.protobuf.message.Message):
    """END RATE SETTINGS

    BEGIN BASIS AND OFFSETS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCHTIME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    SAFETY_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    epochTime: builtins.int
    value: builtins.float
    safety: builtins.float
    date: typing.Text
    def __init__(self,
        *,
        epochTime: typing.Optional[builtins.int] = ...,
        value: typing.Optional[builtins.float] = ...,
        safety: typing.Optional[builtins.float] = ...,
        date: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["date",b"date","epochTime",b"epochTime","safety",b"safety","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["date",b"date","epochTime",b"epochTime","safety",b"safety","value",b"value"]) -> None: ...
global___Offset = Offset

class BasisAndOffsets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BASIS_FIELD_NUMBER: builtins.int
    OFFSETS_FIELD_NUMBER: builtins.int
    basis: builtins.float
    @property
    def offsets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Offset]: ...
    def __init__(self,
        *,
        basis: typing.Optional[builtins.float] = ...,
        offsets: typing.Optional[typing.Iterable[global___Offset]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["basis",b"basis"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["basis",b"basis","offsets",b"offsets"]) -> None: ...
global___BasisAndOffsets = BasisAndOffsets

class TermRateAdjustment(google.protobuf.message.Message):
    """END BASIS AND OFFSETS

    BEGIN RATES

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIME_FIELD_NUMBER: builtins.int
    TIMEUNIT_FIELD_NUMBER: builtins.int
    RATEADJUSTMENT_FIELD_NUMBER: builtins.int
    RATEADJUSTMENTTYPE_FIELD_NUMBER: builtins.int
    time: builtins.int
    timeUnit: global___TimeUnit.ValueType
    rateAdjustment: builtins.float
    rateAdjustmentType: global___RateAdjustmentType.ValueType
    def __init__(self,
        *,
        time: typing.Optional[builtins.int] = ...,
        timeUnit: typing.Optional[global___TimeUnit.ValueType] = ...,
        rateAdjustment: typing.Optional[builtins.float] = ...,
        rateAdjustmentType: typing.Optional[global___RateAdjustmentType.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["rateAdjustment",b"rateAdjustment","rateAdjustmentType",b"rateAdjustmentType","time",b"time","timeUnit",b"timeUnit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["rateAdjustment",b"rateAdjustment","rateAdjustmentType",b"rateAdjustmentType","time",b"time","timeUnit",b"timeUnit"]) -> None: ...
global___TermRateAdjustment = TermRateAdjustment

class DateRateAdjustment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCHTIME_FIELD_NUMBER: builtins.int
    RATEADJUSTMENT_FIELD_NUMBER: builtins.int
    RATEADJUSTMENTTYPE_FIELD_NUMBER: builtins.int
    USEEXPLICITDATE_FIELD_NUMBER: builtins.int
    epochTime: builtins.int
    rateAdjustment: builtins.float
    rateAdjustmentType: global___RateAdjustmentType.ValueType
    useExplicitDate: builtins.bool
    def __init__(self,
        *,
        epochTime: typing.Optional[builtins.int] = ...,
        rateAdjustment: typing.Optional[builtins.float] = ...,
        rateAdjustmentType: typing.Optional[global___RateAdjustmentType.ValueType] = ...,
        useExplicitDate: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["epochTime",b"epochTime","rateAdjustment",b"rateAdjustment","rateAdjustmentType",b"rateAdjustmentType","useExplicitDate",b"useExplicitDate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["epochTime",b"epochTime","rateAdjustment",b"rateAdjustment","rateAdjustmentType",b"rateAdjustmentType","useExplicitDate",b"useExplicitDate"]) -> None: ...
global___DateRateAdjustment = DateRateAdjustment

class PremiumRates(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BASERATE_FIELD_NUMBER: builtins.int
    TERMRATEADJUSTMENTS_FIELD_NUMBER: builtins.int
    PERMARKET_FIELD_NUMBER: builtins.int
    baseRate: builtins.float
    @property
    def termRateAdjustments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TermRateAdjustment]: ...
    perMarket: builtins.bool
    def __init__(self,
        *,
        baseRate: typing.Optional[builtins.float] = ...,
        termRateAdjustments: typing.Optional[typing.Iterable[global___TermRateAdjustment]] = ...,
        perMarket: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["baseRate",b"baseRate","perMarket",b"perMarket"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["baseRate",b"baseRate","perMarket",b"perMarket","termRateAdjustments",b"termRateAdjustments"]) -> None: ...
global___PremiumRates = PremiumRates

class StockRates(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BASERATE_FIELD_NUMBER: builtins.int
    TERMRATEADJUSTMENTS_FIELD_NUMBER: builtins.int
    DATERATEADJUSTMENTS_FIELD_NUMBER: builtins.int
    baseRate: builtins.float
    @property
    def termRateAdjustments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TermRateAdjustment]: ...
    @property
    def dateRateAdjustments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DateRateAdjustment]: ...
    def __init__(self,
        *,
        baseRate: typing.Optional[builtins.float] = ...,
        termRateAdjustments: typing.Optional[typing.Iterable[global___TermRateAdjustment]] = ...,
        dateRateAdjustments: typing.Optional[typing.Iterable[global___DateRateAdjustment]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["baseRate",b"baseRate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["baseRate",b"baseRate","dateRateAdjustments",b"dateRateAdjustments","termRateAdjustments",b"termRateAdjustments"]) -> None: ...
global___StockRates = StockRates

class DividendRates(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BASERATE_FIELD_NUMBER: builtins.int
    TERMRATEADJUSTMENTS_FIELD_NUMBER: builtins.int
    DATERATEADJUSTMENTS_FIELD_NUMBER: builtins.int
    baseRate: builtins.float
    @property
    def termRateAdjustments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TermRateAdjustment]: ...
    @property
    def dateRateAdjustments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DateRateAdjustment]: ...
    def __init__(self,
        *,
        baseRate: typing.Optional[builtins.float] = ...,
        termRateAdjustments: typing.Optional[typing.Iterable[global___TermRateAdjustment]] = ...,
        dateRateAdjustments: typing.Optional[typing.Iterable[global___DateRateAdjustment]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["baseRate",b"baseRate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["baseRate",b"baseRate","dateRateAdjustments",b"dateRateAdjustments","termRateAdjustments",b"termRateAdjustments"]) -> None: ...
global___DividendRates = DividendRates

class VolatilitySettings(google.protobuf.message.Message):
    """END RATES

    BEGIN VOLATILITY SETTINGS

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VOLATILITYTYPE_FIELD_NUMBER: builtins.int
    VOLATILITYSCRIPTNAME_FIELD_NUMBER: builtins.int
    BOOTSTRAPSCRIPTNAME_FIELD_NUMBER: builtins.int
    volatilityType: global___VolatilityType.ValueType
    volatilityScriptName: typing.Text
    bootstrapScriptName: typing.Text
    def __init__(self,
        *,
        volatilityType: typing.Optional[global___VolatilityType.ValueType] = ...,
        volatilityScriptName: typing.Optional[typing.Text] = ...,
        bootstrapScriptName: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bootstrapScriptName",b"bootstrapScriptName","volatilityScriptName",b"volatilityScriptName","volatilityType",b"volatilityType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bootstrapScriptName",b"bootstrapScriptName","volatilityScriptName",b"volatilityScriptName","volatilityType",b"volatilityType"]) -> None: ...
global___VolatilitySettings = VolatilitySettings

class SABRParameter(google.protobuf.message.Message):
    """END VOLATILITY SETTINGS

    BEGIN SABR VOLATILITY

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCHTIME_FIELD_NUMBER: builtins.int
    ALPHA_FIELD_NUMBER: builtins.int
    BETA_FIELD_NUMBER: builtins.int
    VOLVOL_FIELD_NUMBER: builtins.int
    RHO_FIELD_NUMBER: builtins.int
    DOWNCUTOFF_FIELD_NUMBER: builtins.int
    DOWNSLOPE_FIELD_NUMBER: builtins.int
    DOWNCURVATURE_FIELD_NUMBER: builtins.int
    UPCUTOFF_FIELD_NUMBER: builtins.int
    UPSLOPE_FIELD_NUMBER: builtins.int
    UPCURVATURE_FIELD_NUMBER: builtins.int
    epochTime: builtins.int
    alpha: builtins.float
    beta: builtins.float
    volVol: builtins.float
    rho: builtins.float
    downCutOff: builtins.float
    downSlope: builtins.float
    downCurvature: builtins.float
    upCutOff: builtins.float
    upSlope: builtins.float
    upCurvature: builtins.float
    def __init__(self,
        *,
        epochTime: typing.Optional[builtins.int] = ...,
        alpha: typing.Optional[builtins.float] = ...,
        beta: typing.Optional[builtins.float] = ...,
        volVol: typing.Optional[builtins.float] = ...,
        rho: typing.Optional[builtins.float] = ...,
        downCutOff: typing.Optional[builtins.float] = ...,
        downSlope: typing.Optional[builtins.float] = ...,
        downCurvature: typing.Optional[builtins.float] = ...,
        upCutOff: typing.Optional[builtins.float] = ...,
        upSlope: typing.Optional[builtins.float] = ...,
        upCurvature: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["alpha",b"alpha","beta",b"beta","downCurvature",b"downCurvature","downCutOff",b"downCutOff","downSlope",b"downSlope","epochTime",b"epochTime","rho",b"rho","upCurvature",b"upCurvature","upCutOff",b"upCutOff","upSlope",b"upSlope","volVol",b"volVol"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alpha",b"alpha","beta",b"beta","downCurvature",b"downCurvature","downCutOff",b"downCutOff","downSlope",b"downSlope","epochTime",b"epochTime","rho",b"rho","upCurvature",b"upCurvature","upCutOff",b"upCutOff","upSlope",b"upSlope","volVol",b"volVol"]) -> None: ...
global___SABRParameter = SABRParameter

class SABRVolatility(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SABRCALLPARAMETERS_FIELD_NUMBER: builtins.int
    SABRPUTPARAMETERS_FIELD_NUMBER: builtins.int
    @property
    def sabrCallParameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SABRParameter]: ...
    @property
    def sabrPutParameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SABRParameter]: ...
    def __init__(self,
        *,
        sabrCallParameters: typing.Optional[typing.Iterable[global___SABRParameter]] = ...,
        sabrPutParameters: typing.Optional[typing.Iterable[global___SABRParameter]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sabrCallParameters",b"sabrCallParameters","sabrPutParameters",b"sabrPutParameters"]) -> None: ...
global___SABRVolatility = SABRVolatility

class ManualVolatilityStrike(google.protobuf.message.Message):
    """END SABR VOLATILITY

    BEGIN MANUAL VOLATILITY

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STRIKE_FIELD_NUMBER: builtins.int
    VOLATILITY_FIELD_NUMBER: builtins.int
    strike: builtins.float
    volatility: builtins.float
    def __init__(self,
        *,
        strike: typing.Optional[builtins.float] = ...,
        volatility: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["strike",b"strike","volatility",b"volatility"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["strike",b"strike","volatility",b"volatility"]) -> None: ...
global___ManualVolatilityStrike = ManualVolatilityStrike

class ManualVolatilityExpiration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPOCHTIME_FIELD_NUMBER: builtins.int
    STRIKES_FIELD_NUMBER: builtins.int
    epochTime: builtins.int
    @property
    def strikes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ManualVolatilityStrike]: ...
    def __init__(self,
        *,
        epochTime: typing.Optional[builtins.int] = ...,
        strikes: typing.Optional[typing.Iterable[global___ManualVolatilityStrike]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["epochTime",b"epochTime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["epochTime",b"epochTime","strikes",b"strikes"]) -> None: ...
global___ManualVolatilityExpiration = ManualVolatilityExpiration

class ManualVolatility(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CALLEXPIRATIONS_FIELD_NUMBER: builtins.int
    PUTEXPIRATIONS_FIELD_NUMBER: builtins.int
    @property
    def callExpirations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ManualVolatilityExpiration]: ...
    @property
    def putExpirations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ManualVolatilityExpiration]: ...
    def __init__(self,
        *,
        callExpirations: typing.Optional[typing.Iterable[global___ManualVolatilityExpiration]] = ...,
        putExpirations: typing.Optional[typing.Iterable[global___ManualVolatilityExpiration]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["callExpirations",b"callExpirations","putExpirations",b"putExpirations"]) -> None: ...
global___ManualVolatility = ManualVolatility
